export const animeData = [
    {
        id: 1,
        imageUrl:"https://cdn.myanimelist.net/images/anime/1987/117507.jpg",
        DiaimageUrl:"https://cdn.myanimelist.net/images/anime/1987/117507.jpg",
        title:"86 (Eighty-six)",
        Year:"2021",
        eps:"11",
        season:"1",
        stats:"Finished",
        synopsis:"86 bercerita tentang peperangan berkepanjangan antara Republik San Mongolia melawan Kekaisaran Giadian yang berlangsung beberapa tahun kebelakangan. Selama peperangan tersebut RSM di serang oleh drone tanpa awak milik Kekaisaran Giadian yang disebut Legiun. Milizé Vladilena atau Lena menjadi Handler orang yang memandu para drone milik RSM. Dan dirinya di tugaskan menjadi Handler skuadron Spearhead untuk menggantikan Handler mereka sebelumnya. Lena tau kalau mereka yang tinggal disana bukanlah robot dan dipaksa berjuang dalam pertempuran melawan Legiun. Disisi lain ada Nouzen Shinei atau Shin yang merupakan pemimpin di skuadron Spearhead dan yang paling kuat di satuan tersebut. Shin sendiri adalah pemimpin yang dingin, hebat dalam mempredeksi peperangan dan melindungi pasukannya. Hampir setiap peperangan dirinya tidak perlu bimbingan dari Handler. Ini lah kisah dua orang yang berjuang dalam peperangan dari dua sisi yang berbeda; Shin bertindak langsung di medan perang, sementara Lena mengomando detasemen 86 dari jauh dengan bantuan alat komunikasi khusus. Kisah perjuangan dan perpisahan yang menyedihkan keduanya pun dimulai.",
        Skor:"8.28",
        Author:"Asato Asato",
        Genre:"Action, Mecha, Military",
        WatchUrl:"https://stream2.otakuturu.app/web/index.html#!/details?id=61fef9950910d9062c2656db77f6b1ce&context=tvshows&serverId=1b7779efbf81436aaac185d4b27dadbb",
        RevUrl:"https://kusonime.com/86-batch-sub-indo/"
    },

    {
        "id":2,
        imageUrl:"https://assets.ayobandung.com/crop/0x0:0x0/x/photo/2022/12/08/2041202960.jpeg",
        DiaimageUrl:"https://cdn.myanimelist.net/images/anime/1499/131676l.jpg",
        title:"Black Clover: Sword of the Wizard King",
        Year:"2023",
        synopsis:"Asta dan Yuno ditinggalkan di gereja yang sama pada hari yang sama. Dibesarkan bersama sebagai anak-anak, mereka mengetahui tentang Raja Penyihir—gelar yang diberikan kepada penyihir terkuat di kerajaan—dan berjanji bahwa mereka akan bersaing satu sama lain untuk memperebutkan posisi Raja Penyihir berikutnya. Namun, saat mereka tumbuh dewasa, perbedaan mencolok di antara mereka menjadi jelas. Sementara Yuno mampu menggunakan sihir dengan kekuatan dan kontrol yang luar biasa, Asta tidak dapat menggunakan sihir sama sekali dan berusaha mati-matian untuk membangkitkan kekuatannya dengan berlatih secara fisik.Yuno dianugerahi Grimoire yang spektakuler dengan semanggi berdaun empat, sementara Asta tidak menerima apa pun. Namun, segera setelah itu, Yuno diserang oleh seseorang bernama Lebuty, yang tujuan utamanya adalah untuk mendapatkan Grimoire milik Yuno. Asta mencoba melawan Lebuty, tetapi dia kalah. Melepaskan emosi batinnya dalam kemarahan, Asta menerima Grimoire semanggi berdaun lima yang memberinya kekuatan yang cukup untuk mengalahkan Lebuty. Beberapa hari kemudian, kedua sahabat itu pergi ke dunia luar, keduanya mencari tujuan yang sama—menjadi Raja Penyihir!",
        Skor:"8.14",
        Author:"Yuki Tabata",
        Genre:"Action, Fantasy, Comedy",
        WatchUrl:"https://stream2.otakuturu.app/web/index.html#!/details?id=ad7749115329ed1116d9ed6ce1e68140&serverId=1b7779efbf81436aaac185d4b27dadbb",
        RevUrl:"https://www.otakuturu.app/2023/06/black-clover-mahou-multisubs.html",

    },

    {
        id:3,
        imageUrl:"https://stream2.otakuturu.app/Items/a1b69c3ee0b2e8e5ffd50a6f9e6739c7/Images/Primary?fillHeight=706&fillWidth=480&quality=96&tag=0f6a1db6e18c4cc6983963e0a340bda0",
        DiaimageUrl:"https://djm-aaa1.kxcdn.com/resources/upload/products/81woIOXGv7L._AC_SL1500_.jpg",
        title:"Bocchi The Rock",
        Year:"2022",
        "synopsis":"Bocchi the Rock! anime santai ini akan berpusat pada Hitori Gotou atau sering di panggil dengan Bochi-chan, seorang gadis yang dari kecil tidak pernah dapat teman. Tapi ketika dia mengenal musik, kehidupannya mulai berubah. Bahkan Bocchi-chan yang pemalu pun ingin memiliki band yang terlihat bersinar di atas panggung.Namun, karena ia tak memiliki teman, saat SMP ia menghabiskan 6 jam sehari bermain gitar sendirian. Bocchi-chan berdelusi petikan gitarnya sudah baik dan memposting video penampilan gitarnya di internet sebagai “Guitar Hero”. Namun kehidupan Bocchi mulai berubah ketika dia bertemu dengan Nijika Ijichi, gadis yang bermain drummer dari Kessoku Band. Semejak itu kehidupan Bochhi yang penyendiri lambat laun mulai berubah. Dia mulai mendapatkan teman satu band, nongkrong bareng, kerja sambilan yang tidak pernah dia lakukan sebelumnya.Meskipun penampilan pertama mereka bersama di bawah standar, gadis-gadis itu merasa diberdayakan oleh kecintaan mereka yang sama terhadap musik, dan kita segera bergabung kembali dengan Kita. Menemukan kebahagiaan dalam tampil, Bocchi dan rekan bandnya berusaha keras untuk berkembang sebagai musisi sambil memanfaatkan hari-hari sekolah menengah mereka yang singkat.",
        Skor:"8.85",
        Author:"Aki Hamaji",
        Genre:"Comedy, Slice of Life",
        WatchUrl:"https://stream2.otakuturu.app/web/index.html#!/details?id=a1b69c3ee0b2e8e5ffd50a6f9e6739c7&context=tvshows&serverId=1b7779efbf81436aaac185d4b27dadbb",
        RevUrl:"https://www.otakuturu.app/2023/01/bocchi-rock-bd-batch-subtitle-indonesia.html",
    },

    {
        "id":4,
        imageUrl:"https://image.api.playstation.com/vulcan/ap/rnd/202106/1704/JzL1NLQvok7Pghe9W5PP2XNV.png",
          DiaimageUrl:"https://cdn.myanimelis,t.net/images/anime/1786/107453l.jpg",
          title:"Kimetsu No Yaiba",
          Year:"2022",
          synopsis:"Sejak kematian ayahnya, beban menghidupi keluarga berada di pundak Tanjirou Kamado. Meski hidup melarat di gunung terpencil, keluarga Kamado bisa menikmati kehidupan yang relatif damai dan bahagia. Suatu hari, Tanjirou memutuskan untuk pergi ke desa setempat untuk menghasilkan sedikit uang dengan menjual arang. Dalam perjalanan pulang, malam tiba, memaksa Tanjirou berlindung di rumah seorang pria aneh, yang memperingatkannya tentang keberadaan setan pemakan daging yang mengintai di hutan pada malam hari. Ketika dia akhirnya tiba di rumah keesokan harinya, dia bertemu dengan pemandangan yang mengerikan — seluruh keluarganya telah dibantai. Lebih buruk lagi, satu-satunya yang selamat adalah saudara perempuannya Nezuko, yang telah berubah menjadi iblis yang haus darah. Dikonsumsi oleh amarah dan kebencian, Tanjirou bersumpah untuk membalaskan dendam keluarganya dan tinggal bersama satu-satunya saudara kandungnya yang tersisa. Bersamaan dengan kelompok misterius yang menyebut diri mereka Korps Pembunuh Iblis, Tanjirou akan melakukan apa pun untuk membunuh iblis dan melindungi sisa-sisa kemanusiaan saudara perempuan tercintanya.",
          Skor:"8.50",
          Author:"Koyoharu Gotogue",
          Genre:"Action, Monster, Fantasy",
          WatchUrl:"https://anoboy.monster/2019/04/nonton-kimetsu-no-yaiba-season-1-2-3/",
          RevUrl:"https://myanimelist.net/anime/38000/Kimetsu_no_Yaiba",
    },
    {
        "id":5,
        imageUrl:"https://cdn.myanimelist.net/images/anime/1171/109222l.jpg",
        DiaimageUrl:"https://cdn.myanimelist.net/images/anime/1171/109222.jpg",
        title:"Jujutsu Kaisen",
        Year:"2020",
        synopsis:"Jujutsu Kaisen adalah dunia dimana para kutukan memakan manusia yang tidak sadar dirinya menjadi mangsa.Anime ini sendiri berpusat pada Itadori Yuji adalah seorang murid SMA yang menghabiskan waktunya merawat kakeknya yang sakit-sakitan. Meski terlihat seperti murid SMA kebanyakan, kekuatan fisiknya yang luar biasa membuatnya menonjol dari murid Iain. Semua ekskul olahraga ingin merekrutnya, namun Itadori justru lebih senang bergaul dengan murid-murid aneh dari ekskul gaib. Suatu hari, ekskul gaib mendapatkan benda terkutuk, namun mereka tak mengetahui teror macam apa yang akan muncul jika segelnya terbuka. Setelah mereka membuka segel berbahayanya itu yang ternyata adalah salah satu jari dari Sukuna dan memancing para kutukan lainnya, lalu menyerang mereka. Disini lah Yuji menyelamatkan 2 orang anggota ekskul gaib bersama dengan salah satu anggota pelajar dari organisasi Jujutsu. Ketika mereka hampir kalah, Yuji memakan salah satu jari milik Sakuna dan dari sini lah Yuji mulai memiliki kekuatan supernatural. Setelah kejadian tersebut Yuji langsung diawasi dan dipaksa masuk ke Jujutsu sebagai wadah Sakuna. Misi utamanya cuman satu mencari semua potongan Sakuna lalu memakannya",
        Skor:"8.64",
        Author:"Gege Akutami",
        Genre:"Action, Comedy, Fantasy, Monster",
        WatchUrl:"https://anoboy.monster/2020/09/jujutsu-kaisen-tv/",
        RevUrl:"https://kusonime.com/jujutsu-kaisen-subtitle-indonesia-19/",
    },
    {
        "id":6,
        imageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/IGbeFv5Ji4W0x530JcSHiQpamY.jpg",
          DiaimageUrl:"https://cdn.myanimelist.net/images/anime/3/67177l.jpg",
          title:"Shigatsu wa Kimi no Uso",
          Year:"2014",
          synopsis:"berbakat dalam bermain piano, yang selalu mendominasi dalam kompetisi dan menjadikannya terkenal di antara para musikus cilik. Setelah ibu sekaligus instrukturnya meninggal dunia, dia mengalami penurunan mental di tengah-tengah suatu pertunjukan pianonya di usia 11 tahun. Trauma yang diderita olehnya menyebabkan Ia kehilangan kemampuan untuk mendengar suara dentingan piano meskipun secara fisik pendengarannya baik-baik saja. Dua tahun berlalu, Kousei tidak pernah menyentuh pianonya dan beranggapan dunianya sebagai dunia yang monoton tanpa warna. Dia pun seakan melepas kehidupannya dan hanya berinteraksi dekat dengan kedua sahabatnya: Tsubaki Sawabe dan Ryota Watari, hingga pada suatu hari, Ia bertemu seseorang yang mengubah hidupnya serta memberikan kembali warna dalam hidupnya: Kaori Miyazono. Kaori adalah seorang pemain biola seumuran Kousei yang bersifat ceria dan penuh semangat serta memiliki gaya bermain musik yang bebas dan ekspresif; berlawanan dengan gaya bermain Kousei yang kaku dan terstuktur. Lambat laun, Kaori menuntun Kousei kembali ke dunia musik dan menunjukkan bahwa permainan musik adalah sebuah hal yang perlu diresapi menggunakan perasaan dan imajinasi. Kousei pun secara perlahan menemukan makna baru dalam permainan musiknya dan juga menaruh perasaan suka kepada Kaori, tanpa menyadari ada alasan tersendiri bagi Kaori untuk menuntun Kousei kembali ke dunia musik.",

          Skor:"8.65",
          Author:"Naoshi Arakawa",
          Genre:"Drama, Supernatural, Romantic,",
          WatchUrl:"https://anoboy.monster/2019/04/nonton-kimetsu-no-yaiba-season-1-2-3/",
          RevUrl:"https://myanimelist.net/anime/38000/Kimetsu_no_Yaiba",
    },
    {
    "id":7,
    imageUrl:"https://cdn.discordapp.com/attachments/1064757310766981191/1086950022026899526/your-name-Primary.jpg",
    DiaimageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/q719jXXEzOoYaps6babgKnONONX.jpg",
    title:"Kimi no Na wa",
    Year:"2016",
    synopsis:"Mitsuha Miyamizu, seorang siswi SMA, ingin sekali menjalani kehidupan sebagai anak laki-laki di kota Tokyo yang sibuk, mimpi yang sangat kontras dibandingkan dengan kehidupannya saat ini di perdesaan. Sedangkan di kota, Taki Tachibana menjalani kehidupan yang sibuk sebagai seorang siswa sekolah menengah sambil bekerja paruh waktu dan memiliki harapan untuk masa depan di dunia arsitektur. Suatu hari, Mitsuha terbangun di sebuah kamar yang bukan miliknya dan tiba-tiba menemukan dirinya menjalani kehidupan idaman di Tokyo, tetapi justru di dalam tubuh Taki! Di sisi lain, Taki mendapati dirinya menjalani kehidupan Mitsuha di pedesaan yang sederhana. Dalam upaya mencari jawaban atas fenomena aneh ini, mereka mulai mencari satu sama lain. Fenomena-fenomena ini tidak dapat terjelaskan oleh akal sehat karena ternyata tubuh Mitsuha masih berada dalam masa lalu. Kimi no Na wa. berkisah seputar tindakan Mitsuha dan Taki, yang mulai memberikan dampak romantis terhadap kehidupan masing-masing, menjalin mereka menjadi sebuah jalinan yang dipersatukan oleh takdir dan sebuah kebetulan dan mengubah masa depan dengan alur time travel.",

    Skor:"8.85",
    Author:"Makoto Shinkai",
    Genre:"Drama, Supernatural, Romantic,",
    WatchUrl:"https://anoboy.monster/2019/04/nonton-kimetsu-no-yaiba-season-1-2-3/",
    RevUrl:"https://myanimelist.net/anime/38000/Kimetsu_no_Yaiba",
    },
        {
            "id":8,
            imageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/3r4LYFuXrg3G8fepysr4xSLWnQL.jpg",
            DiaimageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/3r4LYFuXrg3G8fepysr4xSLWnQL.jpg",
            title:"Spy x Family",
            Year:"2022",
            eps:"25",
            season:"1",
            stats:"Finished Airing",
            synopsis:" Politisi korup, nasionalis yang hiruk pikuk, dan kekuatan penghasut perang lainnya terus-menerus membahayakan lapisan tipis perdamaian antara negara tetangga Ostania dan Westalis. Di kota Berlint yang ramai di Ostania, Twilight memakai nama samaran Loid Forger. Namun, niat sebenarnya adalah untuk mengumpulkan informasi tentang politisi terkemuka Donovan Desmond yang jarang muncul di depan umum di sekolah putranya: Akademi Eden yang bergengsi. Meminta bantuan pegawai balai kota yang belum menikah Yor Briar untuk bertindak sebagai istrinya dan mengadopsi Anya yatim piatu berusia enam tahun yang penasaran sebagai putrinya, Loid menjalankan rencana induknya. Sayangnya bagi Loid, pria dengan bakatnya pun kesulitan memerankan sosok ayah dan suami yang penyayang. Dan seperti halnya Loid yang menyembunyikan identitas aslinya, Yor—yang merupakan pembunuh bawah tanah yang dikenal sebagai Thorn Princess—dan Anya—seorang esper yang bisa membaca pikiran orang—juga tidak punya rencana untuk mengungkapkan rahasia mereka sendiri. Meskipun keluarga sempurna gambar ini dibangun di atas penipuan, para Pemalsu secara bertahap memahami bahwa cinta yang mereka bagi satu sama lain mengalahkan segalanya.",
        
            Skor:"8.61",
            Author:"Tatsuya Endo",
            Genre:"Action, Drama, Romance, Spy",
            WatchUrl:"https://stream2.otakuturu.app/web/index.html#!/details?id=a0c8493b36f338e7fc71fa59c301f1c3&context=tvshows&serverId=1b7779efbf81436aaac185d4b27dadbb",
            RevUrl:"https://kusonime.com/spy-x-family-batch-subtitle-indonesia/",
            },

];

export default animeData;