export const animeData = [
    {
        id: 1,
        imageUrl:"https://cdn.myanimelist.net/images/anime/1987/117507.jpg",
        DiaimageUrl:"https://cdn.myanimelist.net/images/anime/1987/117507.jpg",
        title:"86 (Eighty-six)",
        Year:"2021",
        eps:"11",
        season:"1",
        stats:"Finished",
        synopsis:"86 bercerita tentang peperangan berkepanjangan antara Republik San Mongolia melawan Kekaisaran Giadian yang berlangsung beberapa tahun kebelakangan. Selama peperangan tersebut RSM di serang oleh drone tanpa awak milik Kekaisaran Giadian yang disebut Legiun. Milizé Vladilena atau Lena menjadi Handler orang yang memandu para drone milik RSM. Dan dirinya di tugaskan menjadi Handler skuadron Spearhead untuk menggantikan Handler mereka sebelumnya. Lena tau kalau mereka yang tinggal disana bukanlah robot dan dipaksa berjuang dalam pertempuran melawan Legiun. Disisi lain ada Nouzen Shinei atau Shin yang merupakan pemimpin di skuadron Spearhead dan yang paling kuat di satuan tersebut. Shin sendiri adalah pemimpin yang dingin, hebat dalam mempredeksi peperangan dan melindungi pasukannya. Hampir setiap peperangan dirinya tidak perlu bimbingan dari Handler. Ini lah kisah dua orang yang berjuang dalam peperangan dari dua sisi yang berbeda; Shin bertindak langsung di medan perang, sementara Lena mengomando detasemen 86 dari jauh dengan bantuan alat komunikasi khusus. Kisah perjuangan dan perpisahan yang menyedihkan keduanya pun dimulai.",
        Skor:"8.28",
        Author:"Asato Asato",
        Genre:"Action, Mecha, Military",
        WatchUrl:"https://stream2.otakuturu.app/web/index.html#!/details?id=61fef9950910d9062c2656db77f6b1ce&context=tvshows&serverId=1b7779efbf81436aaac185d4b27dadbb",
        RevUrl:"https://kusonime.com/86-batch-sub-indo/"
    },

    {
        "id":2,
        imageUrl:"https://assets.ayobandung.com/crop/0x0:0x0/x/photo/2022/12/08/2041202960.jpeg",
        DiaimageUrl:"https://cdn.myanimelist.net/images/anime/1499/131676l.jpg",
        title:"Black Clover: Sword of the Wizard King",
        Year:"2023",
        eps:"1",
        season:"1",
        stats:"Finish Airing",
        synopsis:"Asta dan Yuno ditinggalkan di gereja yang sama pada hari yang sama. Dibesarkan bersama sebagai anak-anak, mereka mengetahui tentang Raja Penyihir—gelar yang diberikan kepada penyihir terkuat di kerajaan—dan berjanji bahwa mereka akan bersaing satu sama lain untuk memperebutkan posisi Raja Penyihir berikutnya. Namun, saat mereka tumbuh dewasa, perbedaan mencolok di antara mereka menjadi jelas. Sementara Yuno mampu menggunakan sihir dengan kekuatan dan kontrol yang luar biasa, Asta tidak dapat menggunakan sihir sama sekali dan berusaha mati-matian untuk membangkitkan kekuatannya dengan berlatih secara fisik.Yuno dianugerahi Grimoire yang spektakuler dengan semanggi berdaun empat, sementara Asta tidak menerima apa pun. Namun, segera setelah itu, Yuno diserang oleh seseorang bernama Lebuty, yang tujuan utamanya adalah untuk mendapatkan Grimoire milik Yuno. Asta mencoba melawan Lebuty, tetapi dia kalah. Melepaskan emosi batinnya dalam kemarahan, Asta menerima Grimoire semanggi berdaun lima yang memberinya kekuatan yang cukup untuk mengalahkan Lebuty. Beberapa hari kemudian, kedua sahabat itu pergi ke dunia luar, keduanya mencari tujuan yang sama—menjadi Raja Penyihir!",
        Skor:"8.14",
        Author:"Yuki Tabata",
        Genre:"Action, Fantasy, Comedy",
        WatchUrl:"https://stream2.otakuturu.app/web/index.html#!/details?id=ad7749115329ed1116d9ed6ce1e68140&serverId=1b7779efbf81436aaac185d4b27dadbb",
        RevUrl:"https://www.otakuturu.app/2023/06/black-clover-mahou-multisubs.html",

    },

    {
        id:3,
        imageUrl:"https://stream2.otakuturu.app/Items/a1b69c3ee0b2e8e5ffd50a6f9e6739c7/Images/Primary?fillHeight=706&fillWidth=480&quality=96&tag=0f6a1db6e18c4cc6983963e0a340bda0",
        DiaimageUrl:"https://djm-aaa1.kxcdn.com/resources/upload/products/81woIOXGv7L._AC_SL1500_.jpg",
        title:"Bocchi The Rock",
        Year:"2022",
        "synopsis":"Bocchi the Rock! anime santai ini akan berpusat pada Hitori Gotou atau sering di panggil dengan Bochi-chan, seorang gadis yang dari kecil tidak pernah dapat teman. Tapi ketika dia mengenal musik, kehidupannya mulai berubah. Bahkan Bocchi-chan yang pemalu pun ingin memiliki band yang terlihat bersinar di atas panggung.Namun, karena ia tak memiliki teman, saat SMP ia menghabiskan 6 jam sehari bermain gitar sendirian. Bocchi-chan berdelusi petikan gitarnya sudah baik dan memposting video penampilan gitarnya di internet sebagai “Guitar Hero”. Namun kehidupan Bocchi mulai berubah ketika dia bertemu dengan Nijika Ijichi, gadis yang bermain drummer dari Kessoku Band. Semejak itu kehidupan Bochhi yang penyendiri lambat laun mulai berubah. Dia mulai mendapatkan teman satu band, nongkrong bareng, kerja sambilan yang tidak pernah dia lakukan sebelumnya.Meskipun penampilan pertama mereka bersama di bawah standar, gadis-gadis itu merasa diberdayakan oleh kecintaan mereka yang sama terhadap musik, dan kita segera bergabung kembali dengan Kita. Menemukan kebahagiaan dalam tampil, Bocchi dan rekan bandnya berusaha keras untuk berkembang sebagai musisi sambil memanfaatkan hari-hari sekolah menengah mereka yang singkat.",
        Skor:"8.85",
        Author:"Aki Hamaji",
        Genre:"Comedy, Slice of Life",
        WatchUrl:"https://stream2.otakuturu.app/web/index.html#!/details?id=a1b69c3ee0b2e8e5ffd50a6f9e6739c7&context=tvshows&serverId=1b7779efbf81436aaac185d4b27dadbb",
        RevUrl:"https://www.otakuturu.app/2023/01/bocchi-rock-bd-batch-subtitle-indonesia.html",
    },
    {
        id:4,
        imageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/npdB6eFzizki0WaZ1OvKcJrWe97.jpg",
        DiaimageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/npdB6eFzizki0WaZ1OvKcJrWe97.jpg",
        title:"Chainsaw Man",
        Year:"2022",
        eps:"12",
        season:"1",
        stats:"Finish Airing",
        "synopsis":"Denji dirampok dari kehidupan remajanya yang normal, tidak memiliki apa-apa selain hutang ayahnya yang sangat besar. Teman satu-satunya adalah hewan peliharaannya, Pochita, iblis gergaji mesin, yang dengannya dia membunuh iblis demi uang yang pasti berakhir di saku yakuza. Yang bisa dilakukan Denji hanyalah memimpikan kehidupan yang baik dan sederhana: hidup dengan makanan enak dan pacar cantik di sisinya. Tapi tindakan pengkhianatan rakus oleh yakuza menyebabkan kematian Denji yang brutal dan terlalu cepat, menghancurkan semua harapan dia untuk mencapai kebahagiaan. Hebatnya, kontrak lama memungkinkan Pochita untuk bergabung dengan almarhum Denji dan memberikan kekuatan iblis padanya, mengubahnya menjadi hibrida yang mampu mengubah bagian tubuhnya menjadi gergaji mesin. Karena kemampuan baru Denji menimbulkan risiko yang signifikan bagi masyarakat, pemburu setan elit Biro Keamanan Publik, Makima, membawanya masuk, membiarkannya hidup selama dia mematuhi perintahnya. Dipandu oleh janji kehidupan konten bersama seorang wanita yang menarik, Denji mencurahkan segalanya dan bertarung dengan sekuat tenaga untuk mewujudkan mimpinya yang naif.",
        Skor:"8.58",
        Author:"Tatsuki Fujimoto",
        Genre:"Action, Gore, Monster, Comedy",
        WatchUrl:"https://stream2.otakuturu.app/web/index.html#!/details?id=87f8df724ff90af3d98b494243a6b729&context=tvshows&serverId=1b7779efbf81436aaac185d4b27dadbb",
        RevUrl:"https://kusonime.com/chainsaw-man-batch-subtitle-indonesia/",
    },
    {
        id:5,
        imageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/iigTJJskR1PcjjXqxdyJwVB3BoU.jpg",
        DiaimageUrl:"https://cdn.myanimelist.net/images/anime/1001/121564l.jpg",
        title:"Death Note",
        Year:"2006",
        eps:"37",
        season:"1",
        stats:"Finished",
        "synopsis":"Pembunuhan brutal, pencurian kecil-kecilan, dan kekerasan yang tidak masuk akal mencemari dunia manusia. Sebaliknya, alam dewa kematian adalah sarang perjudian yang membosankan dan tidak berubah. Pelajar Jepang berusia 17 tahun yang cerdik, Light Yagami, dan dewa kematian Ryuk yang sadis berbagi satu keyakinan: dunia mereka busuk. Untuk hiburannya sendiri, Ryuk menjatuhkan Death Note miliknya ke dunia manusia. Light tersandung padanya, menganggap aturan pertamanya konyol: manusia yang namanya tertulis di catatan ini akan mati. Namun, godaannya terlalu besar, dan Light bereksperimen dengan menulis nama penjahat, yang secara mengganggu melakukan pembunuhan pertamanya. Sadar akan kekuatan dewa mengerikan yang telah jatuh ke tangannya, Light—di bawah alias Kira—mengikuti rasa keadilannya yang jahat dengan tujuan akhir membersihkan dunia dari semua pelaku kejahatan. Detektif dalang yang teliti, L, sudah mengikuti jejaknya, tetapi karena kecemerlangan Light menyaingi L, pengejaran besar untuk Kira berubah menjadi pertarungan kecerdasan yang intens yang hanya bisa berakhir ketika salah satu dari mereka mati.",
        Skor:"8.62",
        Author:"Tsugumi Ohba",
        Genre:"Criminal, Fantasy, Psychological",
        WatchUrl:"https://anoboy.monster/2019/08/death-note-streaming/",
        RevUrl:"https://kusonime.com/deathnote-bd-batch-sub-indonesia-10/",
    },

    {
        "id":6,
        imageUrl:"https://image.api.playstation.com/vulcan/ap/rnd/202106/1704/JzL1NLQvok7Pghe9W5PP2XNV.png",
          DiaimageUrl:"https://cdn.myanimelist.net/images/anime/1286/99889l.jpg",
          title:"Kimetsu No Yaiba",
          Year:"2022",
          synopsis:"Sejak kematian ayahnya, beban menghidupi keluarga berada di pundak Tanjirou Kamado. Meski hidup melarat di gunung terpencil, keluarga Kamado bisa menikmati kehidupan yang relatif damai dan bahagia. Suatu hari, Tanjirou memutuskan untuk pergi ke desa setempat untuk menghasilkan sedikit uang dengan menjual arang. Dalam perjalanan pulang, malam tiba, memaksa Tanjirou berlindung di rumah seorang pria aneh, yang memperingatkannya tentang keberadaan setan pemakan daging yang mengintai di hutan pada malam hari. Ketika dia akhirnya tiba di rumah keesokan harinya, dia bertemu dengan pemandangan yang mengerikan — seluruh keluarganya telah dibantai. Lebih buruk lagi, satu-satunya yang selamat adalah saudara perempuannya Nezuko, yang telah berubah menjadi iblis yang haus darah. Dikonsumsi oleh amarah dan kebencian, Tanjirou bersumpah untuk membalaskan dendam keluarganya dan tinggal bersama satu-satunya saudara kandungnya yang tersisa. Bersamaan dengan kelompok misterius yang menyebut diri mereka Korps Pembunuh Iblis, Tanjirou akan melakukan apa pun untuk membunuh iblis dan melindungi sisa-sisa kemanusiaan saudara perempuan tercintanya.",
          Skor:"8.50",
          Author:"Koyoharu Gotogue",
          Genre:"Action, Monster, Fantasy",
          WatchUrl:"https://anoboy.monster/2019/04/nonton-kimetsu-no-yaiba-season-1-2-3/",
          RevUrl:"https://myanimelist.net/anime/38000/Kimetsu_no_Yaiba",
    },
    {
        "id":7,
        imageUrl:"https://cdn.myanimelist.net/images/anime/1171/109222l.jpg",
        DiaimageUrl:"https://cdn.myanimelist.net/images/anime/1171/109222.jpg",
        title:"Jujutsu Kaisen",
        Year:"2020",
        synopsis:"Jujutsu Kaisen adalah dunia dimana para kutukan memakan manusia yang tidak sadar dirinya menjadi mangsa.Anime ini sendiri berpusat pada Itadori Yuji adalah seorang murid SMA yang menghabiskan waktunya merawat kakeknya yang sakit-sakitan. Meski terlihat seperti murid SMA kebanyakan, kekuatan fisiknya yang luar biasa membuatnya menonjol dari murid Iain. Semua ekskul olahraga ingin merekrutnya, namun Itadori justru lebih senang bergaul dengan murid-murid aneh dari ekskul gaib. Suatu hari, ekskul gaib mendapatkan benda terkutuk, namun mereka tak mengetahui teror macam apa yang akan muncul jika segelnya terbuka. Setelah mereka membuka segel berbahayanya itu yang ternyata adalah salah satu jari dari Sukuna dan memancing para kutukan lainnya, lalu menyerang mereka. Disini lah Yuji menyelamatkan 2 orang anggota ekskul gaib bersama dengan salah satu anggota pelajar dari organisasi Jujutsu. Ketika mereka hampir kalah, Yuji memakan salah satu jari milik Sakuna dan dari sini lah Yuji mulai memiliki kekuatan supernatural. Setelah kejadian tersebut Yuji langsung diawasi dan dipaksa masuk ke Jujutsu sebagai wadah Sakuna. Misi utamanya cuman satu mencari semua potongan Sakuna lalu memakannya",
        Skor:"8.64",
        Author:"Gege Akutami",
        Genre:"Action, Comedy, Fantasy, Monster",
        WatchUrl:"https://anoboy.monster/2020/09/jujutsu-kaisen-tv/",
        RevUrl:"https://kusonime.com/jujutsu-kaisen-subtitle-indonesia-19/",
    },
    {
        "id":8,
        imageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/IGbeFv5Ji4W0x530JcSHiQpamY.jpg",
          DiaimageUrl:"https://cdn.myanimelist.net/images/anime/3/67177l.jpg",
          title:"Shigatsu wa Kimi no Uso",
          Year:"2014",
          synopsis:"berbakat dalam bermain piano, yang selalu mendominasi dalam kompetisi dan menjadikannya terkenal di antara para musikus cilik. Setelah ibu sekaligus instrukturnya meninggal dunia, dia mengalami penurunan mental di tengah-tengah suatu pertunjukan pianonya di usia 11 tahun. Trauma yang diderita olehnya menyebabkan Ia kehilangan kemampuan untuk mendengar suara dentingan piano meskipun secara fisik pendengarannya baik-baik saja. Dua tahun berlalu, Kousei tidak pernah menyentuh pianonya dan beranggapan dunianya sebagai dunia yang monoton tanpa warna. Dia pun seakan melepas kehidupannya dan hanya berinteraksi dekat dengan kedua sahabatnya: Tsubaki Sawabe dan Ryota Watari, hingga pada suatu hari, Ia bertemu seseorang yang mengubah hidupnya serta memberikan kembali warna dalam hidupnya: Kaori Miyazono. Kaori adalah seorang pemain biola seumuran Kousei yang bersifat ceria dan penuh semangat serta memiliki gaya bermain musik yang bebas dan ekspresif; berlawanan dengan gaya bermain Kousei yang kaku dan terstuktur. Lambat laun, Kaori menuntun Kousei kembali ke dunia musik dan menunjukkan bahwa permainan musik adalah sebuah hal yang perlu diresapi menggunakan perasaan dan imajinasi. Kousei pun secara perlahan menemukan makna baru dalam permainan musiknya dan juga menaruh perasaan suka kepada Kaori, tanpa menyadari ada alasan tersendiri bagi Kaori untuk menuntun Kousei kembali ke dunia musik.",

          Skor:"8.65",
          Author:"Naoshi Arakawa",
          Genre:"Drama, Supernatural, Romantic,",
          WatchUrl:"https://anoboy.monster/2019/04/nonton-kimetsu-no-yaiba-season-1-2-3/",
          RevUrl:"https://kusonime.com/kimiuso-subtitle-indonesia-1/",
    },
    {
    "id":9,
    imageUrl:"https://cdn.discordapp.com/attachments/1064757310766981191/1086950022026899526/your-name-Primary.jpg",
    DiaimageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/q719jXXEzOoYaps6babgKnONONX.jpg",
    title:"Kimi no Na wa",
    Year:"2016",
    eps:"0",
    season:"0",
    stats:"Movie",
    synopsis:" Mitsuha Miyamizu, seorang siswi SMA, ingin sekali menjalani kehidupan sebagai anak laki-laki di kota Tokyo yang sibuk, mimpi yang sangat kontras dibandingkan dengan kehidupannya saat ini di perdesaan. Sedangkan di kota, Taki Tachibana menjalani kehidupan yang sibuk sebagai seorang siswa sekolah menengah sambil bekerja paruh waktu dan memiliki harapan untuk masa depan di dunia arsitektur. Suatu hari, Mitsuha terbangun di sebuah kamar yang bukan miliknya dan tiba-tiba menemukan dirinya menjalani kehidupan idaman di Tokyo, tetapi justru di dalam tubuh Taki! Di sisi lain, Taki mendapati dirinya menjalani kehidupan Mitsuha di pedesaan yang sederhana. Dalam upaya mencari jawaban atas fenomena aneh ini, mereka mulai mencari satu sama lain. Fenomena-fenomena ini tidak dapat terjelaskan oleh akal sehat karena ternyata tubuh Mitsuha masih berada dalam masa lalu. Kimi no Na wa. berkisah seputar tindakan Mitsuha dan Taki, yang mulai memberikan dampak romantis terhadap kehidupan masing-masing, menjalin mereka menjadi sebuah jalinan yang dipersatukan oleh takdir dan sebuah kebetulan dan mengubah masa depan dengan alur time travel.",

    Skor:"8.85",
    Author:"Makoto Shinkai",
    Genre:"Drama, Supernatural, Romantic,",
    WatchUrl:"https://anoboy.monster/2019/04/nonton-kimetsu-no-yaiba-season-1-2-3/",
    RevUrl:"https://kusonime.com/movie-kimi-no-na-wa-bd-subtitle-indonesia/",
    },
    
    {
        "id":10,
        imageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/vIeu8WysZrTSFb2uhPViKjX9EcC.jpg",
        DiaimageUrl:"https://cdn.myanimelist.net/images/anime/1457/122623l.jpg",
        title:"Suzume",
        Year:"2023",
        eps:"0",
        season:"0",
        stats:"Movie",
        synopsis:"Dalam perjalanannya ke sekolah suatu hari, Suzume Iwato menemukan Souta Munakata, seorang pemuda yang mencari daerah terlantar. Gadis sekolah menengah itu mengarahkan Souta ke reruntuhan terdekat, tetapi karena penasaran murni, dia sendiri memutuskan untuk pergi ke tujuan yang sama. Sesampai di sana, Suzume menemukan sebuah pintu terisolasi dengan alam semesta seperti mimpi yang terletak di luarnya — tempat yang bisa dia lihat dan rasakan, tetapi tidak bisa dimasuki. Sebuah batu aneh tergeletak di tanah di dekatnya, tapi berubah menjadi makhluk seperti kucing dan kabur saat Suzume mengangkatnya. Tiba-tiba ketakutan, dia kembali ke sekolahnya, tidak menyadari bahwa tindakannya membiarkan pintu terbuka akan memiliki konsekuensi. Dengan dirilisnya batu kunci, kejahatan di alam semesta lain sekarang dapat dengan bebas melarikan diri dan menimbulkan kekacauan di seluruh Jepang. Bermaksud untuk memperbaiki kesalahannya yang berbahaya, Suzume bergabung dengan Souta — yang tujuan sebenarnya adalah mencegah kejahatan membusuk — dalam menemukan dan mengunci semua pintu yang terbuka sebelum negara dihancurkan.",
    
        Skor:"8.41",
        Author:"Makoto Shinkai",
        Genre:"Adventure, Fantasy, Romance",
        WatchUrl:"https://stream2.otakuturu.app/web/index.html#!/details?id=22ae400f3865283aeb82bad160aad77e&serverId=1b7779efbf81436aaac185d4b27dadbb",
        RevUrl:"hhttps://www.otakuturu.app/2023/07/suzume-ai-enhanced-multisubs.html",
        },

    {
    "id":11,
    imageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/3r4LYFuXrg3G8fepysr4xSLWnQL.jpg",
    DiaimageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/3r4LYFuXrg3G8fepysr4xSLWnQL.jpg",
    title:"Spy x Family",
    Year:"2022",
    eps:"25",
    season:"1",
    stats:"Finished Airing",
    synopsis:" Politisi korup, nasionalis yang hiruk pikuk, dan kekuatan penghasut perang lainnya terus-menerus membahayakan lapisan tipis perdamaian antara negara tetangga Ostania dan Westalis. Di kota Berlint yang ramai di Ostania, Twilight memakai nama samaran Loid Forger. Namun, niat sebenarnya adalah untuk mengumpulkan informasi tentang politisi terkemuka Donovan Desmond yang jarang muncul di depan umum di sekolah putranya: Akademi Eden yang bergengsi. Meminta bantuan pegawai balai kota yang belum menikah Yor Briar untuk bertindak sebagai istrinya dan mengadopsi Anya yatim piatu berusia enam tahun yang penasaran sebagai putrinya, Loid menjalankan rencana induknya. Sayangnya bagi Loid, pria dengan bakatnya pun kesulitan memerankan sosok ayah dan suami yang penyayang. Dan seperti halnya Loid yang menyembunyikan identitas aslinya, Yor—yang merupakan pembunuh bawah tanah yang dikenal sebagai Thorn Princess—dan Anya—seorang esper yang bisa membaca pikiran orang—juga tidak punya rencana untuk mengungkapkan rahasia mereka sendiri. Meskipun keluarga sempurna gambar ini dibangun di atas penipuan, para Pemalsu secara bertahap memahami bahwa cinta yang mereka bagi satu sama lain mengalahkan segalanya.",

    Skor:"8.61",
    Author:"Tatsuya Endo",
    Genre:"Action, Drama, Romance, Spy",
    WatchUrl:"https://stream2.otakuturu.app/web/index.html#!/details?id=a0c8493b36f338e7fc71fa59c301f1c3&context=tvshows&serverId=1b7779efbf81436aaac185d4b27dadbb",
    RevUrl:"https://kusonime.com/spy-x-family-batch-subtitle-indonesia/",
    },
    {
    "id":12,
    imageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/d82CH1EMSoC2VvYSTxCZHPboJYq.jpg",
    DiaimageUrl:"https://cdn.myanimelist.net/images/anime/1991/123275l.jpg",
    title:"KamiKatsu: Working for God in a Godless World",
    Year:"2023",
    eps:"12",
    season:"1",
    stats:"On Going",
    synopsis:"Di bawah keyakinan bahwa dewa mahakuasa Mitama akan datang untuk menyelamatkannya, Yukito Urabe berpartisipasi dalam ritual untuk menjadi pemimpin baru kultus ayahnya. Tetapi ketika bocah itu tenggelam selama ritual, dia ingin dilahirkan kembali di dunia tanpa dewa atau agama. Kebangkitan kembali di dunia yang sama sekali berbeda tanpa spiritualitas. Dia bertemu dengan seorang gadis menyimpang bernama Aruaru, yang memperkenalkan dia ke desanya. Namun, citranya yang indah tentang masyarakat dunia ini berumur pendek ketika dia menyaksikan bunuh diri kelompok publik dan mempelajari sistem akhir kehidupan negara: setiap saat, pemerintah dapat memerintahkan warga negara mana pun untuk mati. Aruaru dan saudara perempuannya secara paksa dibawa untuk dieksekusi segera setelah itu, mendorong Yukito untuk segera menyelamatkan mereka — tetapi tidak berhasil. Di saat putus asa, Yukito mengingat kembali ajaran ayahnya dan berdoa agar Mitama menyelamatkan mereka. Tampaknya menjawab panggilannya, seorang gadis kecil turun dari langit dan memusnahkan semua orang yang menyakiti Yukito dan teman-temannya. Yang mengejutkan Yukito, gadis itu memperkenalkan dirinya sebagai Mitama.",

    Skor:"6.81",
    Author:"Aoi Akashiro",
    Genre:"Action, Supernatural, Comedy, Fantasy",
    WatchUrl:"https://stream2.otakuturu.app/web/index.html#!/details?id=43885dd400d8ab39f56581ae88abefd9&serverId=1b7779efbf81436aaac185d4b27dadbb",
    RevUrl:"https://www.otakuturu.app/2023/07/kamikatsu-multisubs.html",
    },
    {
    "id":13,
    imageUrl:"https://cdn.myanimelist.net/images/manga/3/188962l.jpg",
    DiaimageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/rOEaKS6jdZacivHnM56NQ4yhccW.jpg",
    title:"Komi-san wa, Comyushou desu",
    Year:"2021",
    eps:"24",
    season:"1",
    stats:"Finish Airing",
    synopsis:"Ini adalah hari pertama Shouko Komi di SMA Swasta Itan yang prestisius, dan dia telah naik status menjadi sekolah Madonna. Dengan rambut hitam panjang dan penampilan yang tinggi dan anggun, dia menarik perhatian siapa saja yang bertemu dengannya. Hanya ada satu masalah — terlepas dari popularitasnya, Shouko sangat buruk dalam berkomunikasi dengan orang lain. Hitohito Tadano adalah anak SMA biasa. Dengan moto hidupnya baca situasi dan pastikan untuk menjauh dari masalah, dia segera menyadari bahwa duduk di sebelah Shouko telah membuatnya menjadi musuh semua orang di kelasnya! Suatu hari, tersingkir secara tidak sengaja. Dia berbohong bahwa dia tidak mendengar apa-apa, menyebabkan Shouko melarikan diri. Tetapi sebelum dia dapat melarikan diri, Hitohito menduga bahwa Shouko tidak dapat berbicara dengan orang lain dengan mudah — pada kenyataannya, dia tidak pernah dapat memiliki satu pun teman. Hitohito memutuskan untuk membantu Shouko dengan tujuannya mendapatkan seratus teman sehingga dia dapat mengatasi gangguan komunikasinya. Apakah dengan pertemuan mereka berdua akan menyembuhkan gangguan komikasinya, atau menumbuhkan benih cinta ?",

    Skor:"8.15",
    Author:"Tomohito Oda",
    Genre:"Slice of Life, Drama, School life",
    WatchUrl:"https://stream2.otakuturu.app/web/index.html#!/details?id=0355249d492454beec4ca20621042c68&context=home&serverId=1b7779efbf81436aaac185d4b27dadbb",
    RevUrl:"https://kusonime.com/komisan-batch-sub-indo/",
    },
    {
    "id":14,
    imageUrl:"https://cdn.myanimelist.net/images/anime/8/36343l.jpg",
    DiaimageUrl:"https://cdn.myanimelist.net/images/anime/11/39717l.jpg",
    title:"Sword Art Online",
    Year:"2012",
    eps:"96",
    season:"5",
    stats:"Finish Airing",
    synopsis:"Sejak perilisan NerveGear yang inovatif, para gamer dari seluruh dunia telah diberi kesempatan untuk mengalami realitas virtual yang benar-benar imersif. Sword Art Online (SAO). Dengan dirilisnya sensasi yang mendunia ini, bermain game tidak pernah terasa lebih hidup. Namun, fantasi idilis dengan cepat menjadi mimpi buruk yang brutal ketika pencipta SAO menjebak ribuan pemain di dalam game. Fungsi log-out telah dihapus, dengan satu-satunya metode melarikan diri yang melibatkan mengalahkan semua seratus level Aincrad yang semakin sulit. Menambah perjuangan, setiap kematian dalam game menjadi permanen, mengakhiri hidup pemain di dunia nyata. Sementara Kazuto Kirito Kirigaya cukup beruntung menjadi beta-tester untuk game tersebut, dia dengan cepat menemukan bahwa terlepas dari kelebihannya, dia tidak dapat mengatasi tantangan SAO sendirian. Bekerja sama dengan Asuna Yuuki dan pemain berbakat lainnya, Kirito berusaha untuk menghadapi cobaan yang tampaknya tidak dapat diatasi secara langsung. Tetapi dengan bos yang sulit dan kultus gelap yang mengancam menghambat kemajuannya, Kirito menemukan bahwa tugas seperti itu lebih mudah diucapkan daripada dilakukan.",

    Skor:"7.20",
    Author:"Reki Kawahara",
    Genre:"Action, Romance, Drama, Adventure",
    WatchUrl:"https://anoboy.monster/2016/09/sword-art-online-sao-season-1-2-3-indo/",
    RevUrl:"https://kusonime.com/sao-batch-sub-indo/",
    },
    {
    "id":15,
    imageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/fcXdJlbSdUEeMSJFsXKsznGwwok.jpg",
    DiaimageUrl:"https://cdn.myanimelist.net/images/anime/1706/114807l.jpg",
    title:"One Piece",
    Year:"1999",
    eps:"1067",
    stats:"On Going",
    synopsis:"Gol D. Roger dikenal sebagai Raja Bajak Laut, makhluk terkuat dan paling terkenal yang pernah mengarungi Grand Line. Penangkapan dan eksekusi Roger oleh Pemerintah Dunia membawa perubahan di seluruh dunia. Kata-kata terakhirnya sebelum kematiannya mengungkapkan keberadaan harta karun terbesar di dunia, One Piece. Pengungkapan inilah yang membawa Zaman Keagungan Bajak Laut, orang-orang yang bermimpi menemukan One Piece—yang menjanjikan kekayaan dan ketenaran yang tak terbatas—dan sangat mungkin puncak kejayaan dan gelar Raja Bajak Laut. Masukkan Monkey D. Luffy, seorang bocah lelaki berusia 17 tahun yang menentang definisi standar Anda tentang bajak laut. Alih-alih persona populer bajak laut yang jahat, keras, dan ompong yang mengobrak-abrik desa untuk bersenang-senang, alasan Luffy menjadi bajak laut adalah salah satu keajaiban murni: pemikiran tentang petualangan menarik yang membawanya ke orang-orang yang menarik dan akhirnya, harta yang dijanjikan. Mengikuti jejak pahlawan masa kecilnya, Luffy dan krunya melakukan perjalanan melintasi Grand Line, mengalami petualangan gila, mengungkap misteri gelap dan melawan musuh yang kuat, semuanya untuk mencapai kekayaan yang paling didambakan—One Piece.",

    Skor:"8.69",
    Author:"Eiichiro Oda",
    Genre:"Adventure, Action, Pirate, Fantasy",
    WatchUrl:"https://anoboy.monster/2016/03/streaming-nonton-one-piece-full/",
    RevUrl:"https://kusonime.com/one-piece-episode-0001-1050-batch-subtitle-indonesia-8/",
    },
    {
    "id":16,
    imageUrl:"https://cdn.myanimelist.net/images/anime/7/72533l.jpg",
    DiaimageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/iE3s0lG5QVdEHOEZnoAxjmMtvne.jpg",
    title:"One Punch Man",
    Year:"2015",
    eps:"24",
    season:"2",
    stats:"Finish Airing",
    synopsis:"Saitama yang tampaknya tidak mengesankan memiliki hobi yang agak unik: menjadi pahlawan. Untuk mengejar impian masa kecilnya, Saitama berlatih tanpa henti selama tiga tahun dengan penuh ambisi dan konsistensi membuat ia kehilangan semua rambutnya dalam prosesnya. Sekarang, Saitama sangat kuat, dia bisa mengalahkan musuh apapun hanya dengan satu pukulan. Namun, karena tidak ada orang yang mampu menandingi kekuatannya telah membawa Saitama ke masalah yang tidak terduga—dia tidak lagi dapat menikmati serunya pertarungan dan menjadi sangat bosan. Suatu hari, Saitama menarik perhatian Genos cyborg berusia 19 tahun, yang menyaksikan kekuatannya dan ingin menjadi murid Saitama. Genos mengusulkan agar keduanya bergabung dengan Asosiasi Pahlawan untuk menjadi pahlawan bersertifikat yang akan diakui atas kontribusi positif mereka kepada masyarakat. Saitama, yang kaget karena tidak ada yang tahu siapa dia, dengan cepat setuju. Bertemu sekutu baru dan menghadapi musuh baru, Saitama memulai perjalanan baru sebagai anggota Asosiasi Pahlawan untuk merasakan keseruan pertempuran yang pernah ia rasakan.",

    Skor:"8.50",
    Author:"Yusuke Murata",
    Genre:"Action, Comedy, Fantasy",
    WatchUrl:"https://anoboy.monster/2016/12/one-punch-man-season-1-2/",
    RevUrl:"https://kusonime.com/opm-batch-sub-indonesia/",
    },
    {
    "id":117,
    imageUrl:"https://cdn.myanimelist.net/images/anime/1818/126435l.jpg",
    DiaimageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/7jSWOc6jWSw5hZ78HB8Hw3pJxuk.jpg",
    title:"Cyberpunk : Edgerunners",
    Year:"2022",
    eps:"10",
    season:"1",
    stats:"Finished",
    synopsis:"Mimpi ditakdirkan untuk mati di Night City, sebuah metropolis futuristik California. Sebagai seorang remaja yang tinggal di daerah kumuh kota, David Martinez berusaha memenuhi harapan seumur hidup ibunya agar dia mencapai puncak Arasaka, perusahaan keamanan terkemuka dunia. Ketika sebuah insiden dengan geng jalanan membuat hidup David berantakan, dia menemukan cyberware Sandevistan — prostetik yang memberikan kecepatan manusia super kepada pemakainya. Dipicu oleh amarah, David menanamkan perangkat itu di punggungnya, menggunakannya untuk membalas dendam pada salah satu penyiksanya. Ini membuatnya dikeluarkan dari akademi, menghancurkan harapannya untuk membuat ibunya bangga. Setelah menyaksikan kemampuan baru David, pencuri data cantik Lucy Kushinada menawarkan untuk bekerja sama dengannya, memberinya tiket keselamatan. Namun, bergaul dengan Lucy memperkenalkan David ke dunia Edgerunners — penjahat cyborg yang akan melanggar hukum apa pun demi uang. Edgerunners sering kehilangan nyawanya, jika cyberware tidak menghancurkan pikiran mereka terlebih dahulu; tetapi dalam perjuangannya untuk bertahan hidup di dalam sistem yang korup, David siap mempertaruhkan segalanya.",

    Skor:"8.61",
    Author:"Mike Pondsmith",
    Genre:"Action, Gore, Psychological, Futuristic",
    WatchUrl:"https://77.105.142.75/tvseries/cyberpunk-edgerunners-2022/",
    RevUrl:"https://kusonime.com/cyberpunk-edgerunners-batch-subtitle-indonesia/",
    },
    {
    "id":18,
    imageUrl:"https://cdn.myanimelist.net/images/anime/1565/111305l.jpg",
    DiaimageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/zAYRe2bJxpWTVrwwmBc00VFkAf4.jpg",
    title:"Naruto Shippuuden",
    Year:"2007",
    eps:"500",
    season:"21",
    stats:"Finished",
    synopsis:"Naruto Shippuuden bercerita kelanjutan dari seri sebelumnya pas dia masih kecil, setelah merantau beberapa tahun bersama Jiraya untuk berguru dan menambahkan kekuatan akhirnya Naruto kembali ke kampung halam di Desa Konohakagure . Naruto jadi semakin kuat dan bisa sedikit di handalkan setelah latihan dia tetap pada cita-cita nya menjadi Hokage. Sekarang Akatsuki, organisasi misterius ninja nakal elit, mendekati rencana besar mereka yang dapat mengancam keselamatan seluruh dunia shinobi. Meskipun Naruto lebih tua dan kejadian menyeramkan tampak di cakrawala, dia telah berubah sedikit dalam kepribadian — masih kasar dan kekanak-kanakan — meskipun dia sekarang jauh lebih percaya diri dan memiliki tekad yang lebih besar untuk melindungi teman dan rumahnya. Mendapatkan kekuatan dari pengalaman dan kesulitannya, Naruto bertekad untuk menjadi yang terkuat untuk melindungi teman teman dan orang yang dia sayangi. Apa pun yang terjadi, Naruto akan melanjutkan perjuangan untuk apa yang penting baginya, bahkan dengan mengorbankan tubuhnya sendiri, dalam kelanjutan saga tentang anak laki-laki yang ingin menjadi Hokage.",

    Skor:"8.26",
    Author:"Masashi Kishimoto",
    Genre:"Adventure, Ninja, Action, Comedy",
    WatchUrl:"https://anoboy.monster/2016/10/naruto-shippuden/",
    RevUrl:"https://kusonime.com/naruto-shippuuden-subtitle-indonesia-batch-13/",
    },
    {
    "id":19,
    imageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/f7vK8pzZIqhyA8sYmBpWmp9Ae7.jpg",
    DiaimageUrl:"https://cdn.myanimelist.net/images/anime/4/50361l.jpg",
    title:"Gintama",
    Year:"2011",
    eps:"367",
    season:"10",
    stats:"Finished",
    synopsis:"Setelah absen satu tahun, Shinpachi Shimura kembali ke Edo, hanya untuk menemukan kejutan yang mengejutkan: Gintoki dan Kagura, sesama anggota Yorozuya, telah menjadi karakter yang sama sekali berbeda! Melarikan diri dari markas Yorozuya dalam kebingungan, Shinpachi menemukan bahwa semua penghuni Edo telah mengalami perubahan yang sangat ekstrim, baik dalam penampilan maupun kepribadian. Yang paling luar biasa, saudara perempuannya Otae telah menikah dengan kepala Shinsengumi dan penguntit tak tahu malu Isao Kondou dan sedang mengandung anak pertama mereka. Bingung, Shinpachi setuju untuk bergabung dengan Shinsengumi atas permintaan Otae dan Kondou dan menemukan transformasi yang lebih mengejutkan terjadi baik di dalam maupun di luar jajaran organisasi. Namun, mengetahui bahwa Wakil Kepala Toushirou Hijikata tetap tidak berubah, Shinpachi dan sekutu Shinsengumi yang tidak terduga berangkat untuk mengembalikan kota Edo seperti yang mereka ingat. Dengan lebih banyak lelucon kotor, parodi lidah-di-pipi, dan referensi tak tahu malu, Gintama 'mengikuti tim Yorozuya melalui lebih banyak kesialan mereka di dunia Edo yang penuh semangat dan asing.",

    Skor:"9.04",
    Author:"Hideaki Sorachi",
    Genre:"Comedy, Action, Sci-Fi",
    WatchUrl:"https://anoboy.monster/2017/01/gintama-season-1-2-3-4-5-6-7/",
    RevUrl:"https://kusonime.com/gtm-subtitle-indonesia-1/",
    },
    {
    "id":20,
    imageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/5ZFUEOULaVml7pQuXxhpR2SmVUw.jpg",
    DiaimageUrl:"https://cdn.myanimelist.net/images/anime/7/74317l.jpg",
    title:"Fullmetal Alchemist : Brotherhood",
    Year:"2009",
    eps:"64",
    season:"1",
    stats:"Finished",
    synopsis:"Setelah eksperimen alkimia yang mengerikan berjalan salah di rumah tangga Elric, ketika mereka mencoba untuk membangkitkan Ibunya yang sudah meninggal Edward dan Alphonse bersaudara ditinggalkan dalam realitas baru yang membawa bencana. Mengabaikan prinsip alkimia yang melarang transmutasi manusia, anak laki-laki itu berusaha menghidupkan kembali ibu mereka yang baru saja meninggal. Sebaliknya, mereka menderita kerugian pribadi yang brutal: tubuh Alphonse hancur sementara Edward kehilangan satu kaki dan kemudian mengorbankan lengan untuk menjaga jiwa Alphonse di dunia fisik dengan mengikatnya ke baju zirah raksasa. Mereka diselamatkan oleh tetangga mereka Pinako Rockbell dan cucunya Winry. Winry menciptakan kaki palsu untuk Edward dengan memanfaatkan automail, logam yang tangguh dan serbaguna yang digunakan dalam robot dan baju besi tempur. Setelah bertahun-tahun pelatihan, Elric bersaudara memulai pencarian untuk memulihkan tubuh mereka dengan menemukan Batu Bertuah — permata yang kuat yang memungkinkan seorang alkemis untuk menentang hukum tradisional Pertukaran Setara. Saat Edward menjadi alkemis terkenal dan mendapatkan julukan Fullmetal, perjalanan anak laki-laki itu melibatkan mereka dalam konspirasi yang berkembang yang mengancam nasib dunia.",

    Skor:"9.10",
    Author:"Hiromu Arakawa",
    Genre:"Sci-Fi, Fantasy, Action, Adventure",
    WatchUrl:"https://anoboy.monster/2019/08/fullmetal-alchemist-brotherhood/",
    RevUrl:"hhttps://kusonime.com/fullmetal-alchemist-brotherhood-bd-batch-subtitle-indonesia-8/",
    },
    {
    "id":21,
    imageUrl:"https://cdn.myanimelist.net/images/anime/1907/134102l.jpg",
    DiaimageUrl:"https://photo.kontan.co.id/photo/2020/12/10/86894998p.jpg",
    title:"Shingekki No Kyoujin",
    Year:"2013",
    eps:"88",
    season:"4",
    stats:"On Going",
    synopsis:"Berabad-abad yang lalu, umat manusia dibantai hingga hampir punah oleh makhluk humanoid mengerikan yang disebut Titans, memaksa manusia bersembunyi ketakutan di balik tembok konsentris yang sangat besar. Apa yang membuat raksasa ini benar-benar menakutkan adalah selera mereka akan daging manusia tidak lahir dari rasa lapar, tetapi tampaknya karena kesenangan. Untuk memastikan kelangsungan hidup mereka, sisa-sisa umat manusia mulai hidup dalam penghalang pertahanan, menghasilkan seratus tahun tanpa satu pun pertemuan titan. Namun, ketenangan yang rapuh itu segera hancur ketika Titan kolosal berhasil menembus tembok luar yang konon tak tertembus, menyalakan kembali perjuangan untuk bertahan hidup melawan kekejian pemakan manusia. Setelah menyaksikan kerugian pribadi yang mengerikan di tangan makhluk yang menyerang, Eren Yeager mendedikasikan hidupnya untuk membasmi mereka dengan mendaftar ke Survey Corps, unit militer elit yang memerangi humanoid tanpa ampun di luar perlindungan tembok. Eren, adik angkatnya Mikasa Ackerman, dan teman masa kecilnya Armin Arlert bergabung dalam perang brutal melawan para Titan dan berlomba untuk menemukan cara mengalahkan mereka sebelum tembok terakhir ditembus.",

    Skor:"8.54",
    Author:"Hajime Isayama",
    Genre:"Action, Gore, Monster, Military",
    WatchUrl:"https://anoboy.monster/2016/04/shingeki-no-kyojin-attack-titan-indo/",
    RevUrl:"https://kusonime.com/snk-batch-subtitle-indonesia/",
    },
    {
    "id":22,
    imageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/ucpgmUR1h5Te1BYegKItoPjOeF7.jpg",
    DiaimageUrl:"https://cdn.myanimelist.net/images/anime/1337/99013l.jpg",
    title:"Hunter x Hunter",
    Year:"2011",
    eps:"148",
    season:"3",
    stats:"Finished",
    synopsis:"Pemburu mengabdikan diri untuk menyelesaikan tugas berbahaya, mulai dari melintasi wilayah dunia yang belum dipetakan hingga menemukan item dan monster langka. Sebelum menjadi Hunter, seseorang harus lulus Ujian Hunter—proses seleksi berisiko tinggi di mana sebagian besar pelamar akhirnya cacat atau lebih buruk lagi, meninggal. Peserta ambisius yang menantang ujian terkenal membawa alasannya sendiri. Apa yang mendorong Gon Freecss yang berusia 12 tahun adalah menemukan Ging, ayahnya, dan seorang Pemburu sendiri. Percaya bahwa dia akan bertemu ayahnya dengan menjadi Hunter, Gon mengambil langkah pertama untuk berjalan di jalan yang sama. Selama Ujian Hunter, Gon berteman dengan mahasiswa kedokteran Leorio Paladiknight, Kurapika yang pendendam, dan mantan pembunuh Killua Zoldyck. Sementara motif mereka sangat berbeda satu sama lain, mereka bersatu untuk tujuan bersama dan mulai menjelajah ke dunia yang berbahaya menghadapi beberapa musuh yang tidak terduga seperti organisasi pembunuh yang bernama Phantom Troupe, Hisoka, mutan semut dan lain lain. Apakah mereka dapat mengembangkan ilmu bela diri mereka sehingga mereka dapat mengalahkan semua musuhnya ?  .",

    Skor:"9.04",
    Author:"Hajime Isayama",
    Genre:"Action, Gore, Monster, Military",
    WatchUrl:"https://anoboy.monster/2016/04/shingeki-no-kyojin-attack-titan-indo/",
    RevUrl:"https://kusonime.com/snk-batch-subtitle-indonesia/",
    },
    {
    "id":23,
    imageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/qpV8kvRfAntV7D4aOOsLIz7OdPc.jpg",
    DiaimageUrl:"https://e1.pxfuel.com/desktop-wallpaper/379/671/desktop-wallpaper-kimi-no-suizou-wo-tabetai.jpg",
    title:"Kimi no Suizou wo Tabetai",
    Year:"2018",
    eps:"0",
    season:"0",
    stats:"Movie",
    synopsis:"seorang kutu buku yang sangat terpisah dari dunia tempat tinggalnya. Dia tidak tertarik pada orang lain dan sangat yakin bahwa tidak ada orang yang tertarik padanya. Kisahnya dimulai ketika dia menemukan sebuah buku tulisan tangan, berjudul Living with Dying. Dia segera mengidentifikasinya sebagai buku harian rahasia milik teman sekelasnya yang populer dan ceria, Sakura Yamauchi. Dia kemudian bercerita tentang penyakit pankreas yang dideritanya dan waktu yang tersisa sangat terbatas. Hanya keluarganya yang tahu tentang penyakitnya yang sudah parah; bahkan sahabat-sahabatnya pun tidak tahu. Terlepas dari pengungkapan ini, dia tidak menunjukkan simpati atas penderitaannya, tetapi terjebak dalam gelombang semangat Sakura yang gigih, dia akhirnya menyerah untuk menemaninya selama sisa hidupnya. Ketika pasangan yang berlawanan kutub ini berinteraksi, hubungan mereka semakin kuat, terjalin melalui pilihan-pilihan yang mereka buat setiap harinya. Sikap acuh tak acuh dan ketidakpastiannya yang tampak mengganggu alur kehidupan sang protagonis yang tanpa ekspresi, perlahan-lahan membuka hatinya saat ia menemukan dan merangkul makna hidup yang sebenarnya.",

    Skor:"8.56",
    Author:"Yoru Sumino",
    Genre:"Drama, Romance",
    WatchUrl:"https://anoboy.monster/2018/12/kimi-no-suizou-wo-tabetai-i-want-to-eat-your-pancreas/",
    RevUrl:"https://kusonime.com/movie-kimisui-sub-indo/",
    },
    {
        "id":24,
        imageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/tNznuhcf7WKzEmPQEsIgGMrB3Az.jpg",
        DiaimageUrl:"https://cdn.myanimelist.net/images/anime/1252/115539.jpg",
        title:"Kobayashi-san Chi no Maid Dragon",
        Year:"2017",
        eps:"34",
        season:"2",
        stats:"Finish Airing",
        synopsis:"Ketika Tooru melanjutkan usahanya untuk menjadi pelayan terhebat dan Kanna Kamui sepenuhnya tenggelam dalam kehidupannya sebagai siswa sekolah dasar, tidak ada hari yang membosankan di rumah tangga Kobayashi dengan kenakalan yang menjadi makanan sehari-hari. Namun, pada suatu hari, tanah longsor besar terlihat di bukit tempat Kobayashi dan Tooru pertama kali bertemu-sebuah tampilan yang jelas dari kekuatan naga. Ketika tidak ada naga yang mereka kenal yang mengaku bertanggung jawab, sang pelaku turun dari langit: Ilulu, Naga Chaos radikal dengan kekuatan mengerikan yang menyaingi Tooru. Muak dengan keterlibatan Tooru dengan manusia, Ilulu menggunakan metode khas naga untuk menyelesaikan konflik - pertempuran sampai mati. Terlepas dari perilaku seperti itu, dia menjadi tertarik dengan kemampuan Kobayashi untuk berteman dengan naga dan memutuskan untuk mengamati apa yang membuat Kobayashi begitu istimewa. Dengan adanya naga baru yang merepotkan di kota, kehidupan eksentrik Kobayashi dengan pelayan naga menjadi semakin menyenangkan.",
    
        Skor:"8.30",
        Author:"Coolkyousinnjya",
        Genre:"Fantasy, Slice of Life",
        WatchUrl:"https://anoboy.monster/2018/01/kobayashi-san-chi-no-maid-dragon-streaming/",
        RevUrl:"https://kusonime.com/kobayashisan-s1-batch-sub-indonesia/",
    },
    {
        "id":25,
        imageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/rxfiH4tL1j1Uf1C6RwMbizWiGNn.jpg",
        DiaimageUrl:"https://cdn.myanimelist.net/images/anime/1819/97947.jpg",
        title:"5-toubun no Hanayome",
        Year:"2019",
        eps:"24",
        season:"2",
        stats:"Finished",
        synopsis:"Fuutarou Uesugi adalah seorang siswa SMA yang berprestasi, tetapi menjalani kehidupan yang sulit. Kepribadiannya yang keras kepala dan sifatnya yang tertutup membuatnya tidak memiliki teman, dan ayahnya terlilit utang, memaksa keluarganya untuk bertahan hidup. Suatu hari saat istirahat makan siang, Uesugi bertengkar dengan seorang siswa pindahan wanita yang telah mengklaim tempat duduknya, yang membuat mereka berdua tidak menyukai satu sama lain. Pada hari yang sama, ia diberi kesempatan emas untuk menghapus utang keluarganya: menjadi guru les privat bagi putri seorang keluarga kaya, dengan upah lima kali lipat dari harga pasar. Dia menerima tawaran itu, tetapi merasa ngeri saat mengetahui bahwa kliennya, Itsuki Nakano, adalah gadis yang dia hadapi sebelumnya! Setelah gagal mencoba untuk kembali ke sisi baik Itsuki, Uesugi menemukan bahwa masalahnya tidak berakhir di situ: Itsuki sebenarnya adalah anak kembar lima, jadi selain dia, dia juga harus mengajari adik-adiknya - Miku, Yotsuba, Nino, dan Ichika - yang, meskipun memiliki ancaman gagal, tidak ingin berhubungan dengan seorang guru. Namun, mata pencaharian keluarganya dipertaruhkan, jadi Uesugi terus maju, bertekad untuk menghilangkan rasa benci mereka terhadap belajar dan berhasil membimbing mereka hingga lulus.",
        
        Skor:"7,66",
        Author:"Negi Haruba",
        Genre:"Comedy, Romance",
        WatchUrl:"https://anoboy.monster/2019/01/gotoubun-no-hanayome-season-1-2/",
        RevUrl:"https://kusonime.com/gotoubun-batch-sub-indo/",
        },
        {
            "id":26,
            imageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/hZydsSAJMwNHekMFKx48VmdqPvM.jpg",
            DiaimageUrl:"https://cdn.myanimelist.net/images/anime/1695/111486.jpg",
            title:"Horimiya",
            Year:"2021",
            eps:"17",
            season:"1",
            stats:"Finish Airing",
            synopsis:"Di permukaan, pemikiran bahwa Kyouko Hori dan Izumi Miyamura akan bergaul akan menjadi hal yang terakhir dalam benak orang. Bagaimanapun juga, Hori memiliki kombinasi sempurna antara kecantikan dan otak, sementara Miyamura tampak lemah lembut dan jauh dari teman-teman sekelasnya. Namun, sebuah pertemuan yang menentukan antara keduanya membuat kedua sisi tersembunyi mereka terbuka. Meskipun dia populer di sekolah, Hori hanya memiliki sedikit waktu untuk bersosialisasi dengan teman-temannya karena pekerjaan rumah. Di sisi lain, Miyamura hidup di bawah pengawasan teman-temannya, tubuhnya penuh dengan tato dan tindikan rahasia yang membuatnya terlihat seperti anak nakal yang lembut. Memiliki kepribadian yang bertolak belakang namun memiliki kesamaan yang aneh, keduanya dengan cepat menjadi teman dan sering menghabiskan waktu bersama di rumah Hori. Ketika mereka berdua keluar dari cangkang mereka, mereka saling berbagi sisi diri mereka yang tersembunyi dari dunia luar.",
        
            Skor:"8.20",
            Author:"Daisuke Hagiwara",
            Genre:"Romance",
            WatchUrl:"https://anoboy.monster/2021/01/horimiya/",
            RevUrl:"https://kusonime.com/horimiya-batch-subtitle-indonesia-1/",
        },
        {
            "id":27,
            imageUrl:"https://www.themoviedb.org/t/p/w300_and_h450_bestv2/5s1pWUZnjtufXMlaUb1YaIzG6Rb.jpg",
            DiaimageUrl:"https://cdn.myanimelist.net/images/manga/2/213693.jpg",
            title:"Wangan Midnight",
            Year:"2007",
            eps:"26",
            season:"1",
            stats:"Finished",
            synopsis:"Akio secara tidak sengaja bertemu dengan rekan sekelasnya, Tatsuya Shima, yang memiliki ketertarikan yang sama dalam dunia balap jalanan. Mereka terlibat dalam balapan jalanan di jalan raya Wangan di Tokyo, yang terkenal dengan akselerasi panjang dan kecepatan tinggi. Akio menggunakan mobilnya yang sudah dimodifikasi untuk menghadapi berbagai lawan tangguh di dunia balap jalanan. Namun, dalam perjalanan balapnya, Akio mengetahui bahwa mobilnya tidak hanya memiliki kecepatan yang menakjubkan, tetapi juga memiliki roh yang jahat. Devil Z memiliki sejarah gelap dan legenda yang mengerikan di dunia balap jalanan. Akio harus belajar mengendalikan mobil ini yang sangat sulit dikendarai dan mengatasi bahaya yang mengintainya. Selama perjalanan Akio di dunia balap jalanan, dia bertemu dengan berbagai karakter menarik dan pesaing tangguh. Dia juga mengembangkan persahabatan dan rivalitas dengan pengemudi lain yang memiliki keterampilan mengemudi yang luar biasa. Akio berusaha untuk menjadi juara balap jalanan terbaik dan mengungkap misteri di balik Devil Z.",
        
            Skor:"7.49",
            Author:"Michiharu Kusunoki",
            Genre:" Action, Award Winning, Drama",
            WatchUrl:"https://nimegami.id/wangan-midnight-bd-sub-indo/",
            RevUrl:"https://kusonime.com/wangan-midnight-batch-subtitle-indonesia/",
        },
    {
    "id":28,
    imageUrl:"https://www.themoviedb.org/t/p/w300_and_h450_bestv2/7C1PMnV0uMrMNcfws5J7aLNxe3Q.jpg",
    DiaimageUrl:"https://cdn.myanimelist.net/images/anime/1384/127972.jpg",
    title:"Initial D",
    Year:"1998",
    eps:"86",
    season:"7",
    stats:"Finished",
    synopsis:"Tidak seperti teman-temannya, Takumi Fujiwara tidak terlalu tertarik pada mobil, dengan sedikit atau bahkan tidak memiliki pengetahuan tentang dunia penggemar mobil dan pembalap jalanan. Sebagai anak dari seorang pemilik toko tahu, ia ditugaskan untuk mengantarkan tahu setiap pagi tanpa henti, mengemudi di sepanjang gunung Akina. Dengan demikian, percakapan mengenai mobil atau mengemudi secara umum hanya akan mengingatkan Takumi pada rutinitas harian yang melelahkan yang dipaksakan kepadanya. Suatu malam, Akagi Red Suns, tim pembalap jalanan yang terkenal, mengunjungi kota Akina untuk menantang jalur gunung setempat. Dipimpin oleh dua pembalap jagoan mereka, Ryousuke dan Keisuke Takahashi, Red Suns berencana untuk menaklukkan semua lintasan balap di Kanto dan menjadikan diri mereka sebagai kru tercepat di wilayah tersebut. Namun, di luar dugaan mereka, salah satu mobil jagoan mereka disalip oleh sebuah Toyota AE86 tua dalam perjalanan pulang ke rumah dari Akina. Setelah kejadian tersebut, Takahashi bersaudara sangat waspada terhadap pengemudi misterius yang memiliki teknik dan pengalaman yang luar biasa di jalanan lokal-AE86 dari Gunung Akina.",

    Skor:"8.33",
    Author:"Shuichi Shigeno",
    Genre:"Action, Dramae",
    WatchUrl:"https://anoboy.monster/2018/06/initial-d-season-1-2-3-4-5-6/",
    RevUrl:"https://kusonime.com/initial-d-batch-sub-indo/",
    },
];

export default animeData;