export const movielistData = [
    {
        id: 1,
        imageUrl:"https://www.themoviedb.org/t/p/original/3Mwj2sIONQckOZP3YwsUXF7U5I4.jpg",
        DiaimageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/kyuXWPU7KLGD6yIfhCVk59LF0KN.jpg",
        title:"In Time",
        Year:"201",
        duration:"1h 49m",
        synopsis:"Dalam waktu yang tidak terlalu lama, gen penuaan telah dimatikan. Untuk menghindari kelebihan populasi, waktu telah menjadi mata uang dan cara orang membayar kemewahan dan kebutuhan. Yang kaya bisa hidup selamanya, sementara yang lain mencoba bernegosiasi untuk keabadian mereka. Seorang pemuda miskin yang datang ke keberuntungan waktu, meskipun terlambat untuk membantu ibunya dari kematian. Dia akhirnya melarikan diri dari kepolisian korup yang dikenal sebagai 'penjaga waktu'.",
        Skor:"6.7",
        Author:"Andrew Niccol",
        Genre:"Action,Thriller, Sci-Fi",
        WatchUrl:"https://77.105.142.75/movie/in-time-2011/",
        RevUrl:"https://www.rottentomatoes.com/m/in_time"
    },
    {
        id: 2,
        imageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/fiVW06jE7z9YnO4trhaMEdclSiC.jpg",
        DiaimageUrl:"https://www.themoviedb.org/t/p/original/2h2Ctf9YN3O7HQFC8ZU6SrzDZrl.jpg",
        title:"Fast X",
        Year:"2023",
        duration:"2h 22m",
        synopsis:"Selama banyak misi dan melawan rintangan yang mustahil, Dom Toretto dan keluarganya telah mengakali, mengalahkan, dan mengalahkan setiap musuh di jalan mereka. Sekarang, mereka menghadapi lawan paling mematikan yang pernah mereka hadapi: Ancaman mengerikan yang muncul dari bayang-bayang masa lalu yang dipicu oleh dendam darah, dan yang bertekad untuk menghancurkan keluarga ini dan menghancurkan segalanya—dan semua orang—yang dicintai Dom, selamanya.",
        Skor:"5.9",
        Author:"Louis Leterrier",
        Genre:"Action, Crime, Thriller",
        WatchUrl:"https://77.105.142.75/movie/fast-x-2023/",
        RevUrl:"https://www.rottentomatoes.com/m/fast_x"
    },
    {
        id: 2,
        imageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/74xTEgt7R36Fpooo50r9T25onhq.jpg ",
        DiaimageUrl:"https://www.themoviedb.org/t/p/original/8gVy5MLXtZBWghMykQtPMsNc5kH.jpg",
        title:"The Batman",
        Year:"2022",
        duration:"2h 57m",
        synopsis:"Disutradarai oleh Matt Reeves, saga lanjutan dari komik superhero Batman menemukan Bruce Wayne (Robert Pattinson) selama masa mudanya, khususnya hanya selama tahun kedua secara diam-diam memerangi kejahatan di Kota Gotham. Saat dia mengungkap plot jahat yang memiliki hubungan dengan keluarganya, Bruce sebagai Batman menghadapi musuh baru seperti Riddler (Paul Dano) dan Penguin (Colin Farrell) saat menemukan sekutu yang ambigu di Selina Kyle, juga dikenal sebagai Catwoman (Zoë Kravitz).",
        Skor:"7.8",
        Author:"Matt Reeves",
        Genre:"Crime, Mystery, Action, Thriller",
        WatchUrl:"https://77.105.142.75/movie/the-batman-2022/",
        RevUrl:"https://www.rottentomatoes.com/m/the_batman"
    },
    {
        id: 6,
        imageUrl:"https://www.themoviedb.org/t/p/original/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg",
        DiaimageUrl:"https://www.themoviedb.org/t/p/original/neG5yuQITkKI6QcmN3l4JbqinTF.jpg",
        title:"The Super Mario Bros. Movie",
        Year:"2023",
        duration:"1h 33m",
        synopsis:"Berdasarkan video game Super Mario, film animasi ini mengikuti Mario dalam petualangannya bersama teman-temannya. Mario bergabung dengan Princess Peach dan Toad. Ketiganya sedang mencari saudara laki-laki Mario, Luigi. Bersama-sama, mereka berharap untuk mengalahkan Bowser yang jahat dan menyelamatkan Kerajaan Jamur dari rencananya yang merusak. Disutradarai oleh Aaron Horvath dan Michael Jelenic. Dibintangi oleh Chris Pratt, Anya Taylor-Joy, Charlie Day, Jack Black, Seth Rogen, dan Keegan-Michael Key.",
        Skor:"7.1",
        Author:"Michael Jelenic",
        Genre:"Animation, Comdey, Adventure",
        WatchUrl:"https://77.105.142.75/movie/the-super-mario-bros-movie-2023/",
        RevUrl:"https://www.rottentomatoes.com/m/the_super_mario_bros_movie"
    },
    {
        id: 3,
        imageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg",
        DiaimageUrl:"https://www.themoviedb.org/t/p/original/9UQMzjDgkapYMrwmvNNSVpAnjsV.jpg",
        title:"Guardian of the Galaxy Vol. 3",
        Year:"2023",
        duration:"2h 30m",
        synopsis:"Menyusul kehilangan cintanya yang mengecewakan, Gamora (Zoe Saldana), Peter Quill (Chris Pratt) menghadapi tugas yang menantang untuk meningkatkan moral tim sampahnya untuk memulai pencarian tanpa larangan di seluruh alam semesta. Quill dan sekutunya harus menjalani ujian baru terhadap ikatan mereka atau menghadapi akhir dari tugas mereka sebagai Penjaga. James Gunn menulis dan menyutradarai bagian ketiga dari waralaba Marvel. Dibintangi bersama Dave Bautista, Vin Diesel, Bradley Cooper, dan Karen Gillan.",
        Skor:"8.2",
        Author:"James Gunn",
        Genre:"Action, Adventure, Comedy, Sci-Fi",
        WatchUrl:"https://77.105.142.75/movie/guardians-of-the-galaxy-volume-3-2023/",
        RevUrl:"https://www.rottentomatoes.com/m/guardians_of_the_galaxy_vol_3"
    },
    {
        id: 5,
        imageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/5ik4ATKmNtmJU6AYD0bLm56BCVM.jpg",
        DiaimageUrl:"https://www.themoviedb.org/t/p/original/8QJcLl8rpOlA3ys6Towbcxbu3UB.jpg",
        title:"Evil Dead Rise",
        Year:"2023",
        duration:"1h 36m",
        synopsis:"Ditulis dan disutradarai oleh Lee Cronin, bagian terbaru dari franchise Evil Dead berpusat pada keluarga yang rumit dan setan yang menghantui mereka. Saudari terasing Beth dan Ellie bersatu kembali setelah bertahun-tahun. Beth mampir ke apartemen Ellie di Los Angeles tempat dia membesarkan ketiga anaknya sebagai ibu tunggal. Para suster menemukan sebuah buku tak menyenangkan yang melepaskan setan yang merasuki daging. Saat iblis menguasai Beth, Ellie dan anak-anaknya menghadapi mimpi terburuk dalam hidup mereka.",
        Skor:"6.6",
        Author:"Lee Cronin",
        Genre:"Horror, Thriller",
        WatchUrl:"https://77.105.142.75/movie/evil-dead-rise-2023/",
        RevUrl:"https://www.rottentomatoes.com/m/evil_dead_rise"
    },
    {
        id: 4,
        imageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/ym1dxyOk4jFcSl4Q2zmRrA5BEEN.jpg ",
        DiaimageUrl:"https://www.themoviedb.org/t/p/original/dnHsot6s6Tv0XpLJxNtfg3P6C85.jpg",
        title:"The Little Mermaid",
        Year:"2023",
        duration:"2h 15m",
        synopsis:"Ariel, seorang putri duyung, penasaran dengan semua hal tentang manusia. Ariel meminta penyihir laut Ursula untuk mengambil suaranya sebagai ganti kaki, karena ini adalah satu-satunya cara dia bisa menjelajahi dunia manusia Eric, kekasihnya. Ayahnya yang frustrasi, Raja Triton, khawatir. Tapi teman makhluk laut tepercaya Flounder dan Sebastian masih mengawasinya.",
        Skor:"7.2",
        Author:"Rob Marshall",
        Genre:"Adventure, Family, Fantasy, Romance",
        WatchUrl:"https://77.105.142.75/movie/the-little-mermaid-2023/",
        RevUrl:"https://www.rottentomatoes.com/m/the_little_mermaid_2023"
    },
    {
        id: 4,
        imageUrl:"https://www.themoviedb.org/t/p/original/d1qDrtlRP3adVFhGlGiLLMutmRd.jpg",
        DiaimageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/7gKI9hpEMcZUQpNgKrkDzJpbnNS.jpg",
        title:"Extraction 2",
        Year:"2023",
        duration:"2h 3m",
        synopsis:"Ditugaskan untuk mengekstraksi sebuah keluarga yang berada di bawah kekuasaan seorang gangster Georgia, Tyler Rake menyusup ke salah satu penjara paling mematikan di dunia untuk menyelamatkan mereka. Tetapi ketika ekstraksi menjadi panas, dan gangster itu mati dalam panasnya pertempuran, saudara laki-lakinya yang sama kejamnya melacak Rake dan timnya ke Wina, untuk membalas dendam.",
        Skor:"7.1",
        Author:"Sam Hargrave",
        Genre:"Action, Thriller",
        WatchUrl:"https://77.105.142.75/movie/extraction-2-2023/",
        RevUrl:"https://www.rottentomatoes.com/m/extraction_2"
    },
    {
        id: 5,
        imageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/62HCnUTziyWcpDaBO2i1DX17ljH.jpg ",
        DiaimageUrl:"https://www.themoviedb.org/t/p/original/o4dhtrJuvrmHwBe7LYJwoGVPwRq.jpg",
        title:"Top Gun: Maverick",
        Year:"2022",
        duration:"2h 11m",
        synopsis:"Setelah lebih dari tiga puluh tahun mengabdi sebagai salah satu penerbang top Angkatan Laut, Pete Maverick Mitchell (Tom Cruise) adalah tempatnya, mendorong amplop sebagai pilot uji yang berani dan menghindari kenaikan pangkat yang akan membuatnya jatuh. Ketika dia menemukan dirinya melatih detasemen lulusan Top Gun untuk misi khusus yang belum pernah dilihat oleh pilot yang masih hidup, Maverick bertemu dengan Lt. Bradley Bradshaw (Miles Teller), tanda panggilan: Rooster, putra mendiang teman Maverick dan Radar Intercept Officer Lt. Nick Bradshaw, alias “Goose”.",
        Skor:"8.3",
        Author:"Joseph Kosinki",
        Genre:"Action, Drama",
        WatchUrl:"https://77.105.142.75/movie/top-gun-maverick-2022/",
        RevUrl:"https://www.rottentomatoes.com/m/top_gun_maverick"
    },
    {
        id: 3,
        imageUrl:"https://www.themoviedb.org/t/p/original/vppo7eOOkkjoSoBSglYIxLDB0dJ.jpg",
        DiaimageUrl:"https://www.themoviedb.org/t/p/original/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
        title:"John Wick: Chapter 4",
        Year:"2023",
        duration:"2h 50m",
        synopsis:"Dengan harga di kepalanya yang terus meningkat, John Wick menemukan jalan untuk mengalahkan The High Table. Tapi sebelum dia bisa mendapatkan kebebasannya, Wick harus bertahan hidup dan berhadapan dengan musuh baru dengan aliansi yang kuat di seluruh dunia yang merupakan instrumen kuat dari high table dan kekuatan yang mengubah teman lama menjadi musuh.",
        Skor:"7.9",
        Author:"Chad Stahelski",
        Genre:"Action, Crime, Thriller",
        WatchUrl:"https://77.105.142.75/movie/john-wick-chapter-4-2023/",
        RevUrl:"https://www.rottentomatoes.com/m/john_wick_chapter_4"
    },
    {
        id: 6,
        imageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/rJHC1RUORuUhtfNb4Npclx0xnOf.jpg",
        DiaimageUrl:"https://www.themoviedb.org/t/p/original/tlZpSxYuBRoVJBOpUrPdQe9FmFq.jpg",
        title:"Uncharted",
        Year:"2022",
        duration:"1h 56m",
        synopsis:"Pemberani dua puluhan Nathan Drake (Tom Holland) menginginkan kehidupan petualangan. Saat berpapasan dengan Victor Sullivan (Mark Wahlberg) yang masam, duo petualang ini memulai pencarian internasional berisiko tinggi untuk menemukan harta karun kuno yang paling sulit dipahami di dunia. Sepanjang jalan, mereka menemukan bukti yang dapat mengarah pada keberadaan saudara laki-laki Drake yang terasing",
        Skor:"6.3",
        Author:"Ruben Fleischer",
        Genre:"Action, Adventure",
        WatchUrl:"https://77.105.142.75/movie/uncharted-2022/",
        RevUrl:"https://www.rottentomatoes.com/m/uncharted_2022"
    },
    {
        id: 7,
        imageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
        DiaimageUrl:"https://www.themoviedb.org/t/p/original/aV1KGO9X3S4kzqEptVDAvGjccql.jpg",
        title:"Puss in Boots: The Last Wish",
        Year:"2022",
        duration:"1h 43m",
        synopsis:"Terlepas dari kegemarannya untuk berpetualang dan berani, Puss in Boots (Antonio Banderas) yang terkenal petualang menerima kebangkitan yang kasar ketika dia menemukan bahwa delapan dari sembilan nyawanya telah digunakan untuk melakukan prestasi seperti itu. Dia kemudian harus memulai satu pencarian terakhir untuk menemukan sumber sihir yang mampu memulihkan kekuatan hidupnya sepenuhnya.",
        Skor:"7.9",
        Author:"Joel Crawford",
        Genre:"Animation, Family, Adventure",
        WatchUrl:"https://77.105.142.75/movie/puss-in-boots-the-last-wish-2022/",
        RevUrl:"https://www.rottentomatoes.com/m/puss_in_boots_the_last_wish"
    },
    {
        id: 7,
        imageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/7oWY8VDWW7thTzWh3OKYRkWUlD5.jpg",
        DiaimageUrl:"https://www.themoviedb.org/t/p/original/xmbpoYp2BBCsKy8BfJzeh6SMepA.jpg",
        title:"Django Unchained",
        Year:"2012",
        duration:"2h 45m",
        synopsis:"Seorang mantan budak dan pemburu hadiah Jerman menjadi sekutu yang tidak terduga dalam pertempuran melawan pemilik perkebunan tirani di barat ini dari visioner.King Schultz tiba di Amerika bertekad untuk menangkap penjahat Brittle bersaudara hidup atau mati. Di tengah pencariannya, Dr. Schultz berpapasan dengan Django (pemenang Academy Award Jamie Foxx), seorang budak yang dibebaskan dan pelacak terampil yang berusaha menyelamatkan istri tercintanya Broomhilda dari pemilik perkebunan kejam Calvin Candie . Setelah Django membantu Dr. Schultz dalam menangkap Brittle bersaudara, keduanya bekerja sama untuk menangkap beberapa orang yang paling dicari di Selatan.",
        Skor:"8.4",
        Author:"Quentin Tarantino",
        Genre:"Drama, Western, Action",
        WatchUrl:"https://77.105.142.75/movie/django-unchained-2012/",
        RevUrl:"https://www.rottentomatoes.com/m/django_unchained_2012"
    },
    {
        id: 8,
        imageUrl:"https://www.themoviedb.org/t/p/original/5JcuLWpKf85q5oy1NbzyFAGkhqx.jpg",
        DiaimageUrl:"https://www.themoviedb.org/t/p/original/qnqGbB22YJ7dSs4o6M7exTpNxPz.jpg",
        title:"Ant-Man and the Wasp: Quantumania",
        Year:"2023",
        duration:"2h 5m",
        synopsis:"Film terbaru dalam franchise Scott Lang dan Hope Van Dyne diseret ke Alam Kuantum, bersama dengan orang tua Hope dan putri Scott, Cassie. Bersama-sama mereka harus menemukan cara untuk melarikan diri, tetapi rahasia apa yang disembunyikan ibu Hope? Dan siapa Kang yang misterius itu?",
        Skor:"6.1",
        Author:"Peyton Reed",
        Genre:"Action, Fantasy, Sci-Fi",
        WatchUrl:"https://77.105.142.75/movie/ant-man-and-the-wasp-quantumania-2023/",
        RevUrl:"https://www.rottentomatoes.com/m/ant_man_and_the_wasp_quantumania"
    },
    {
        id: 7,
        imageUrl:"https://www.themoviedb.org/t/p/original/ygO9lowFMXWymATCrhoQXd6gCEh.jpg",
        DiaimageUrl:"https://www.themoviedb.org/t/p/original/fXu1siEaLueAY2NGR7vxv13rqZ1.jpg",
        title:"Sisu",
        Year:"2023",
        duration:"1h 31m",
        synopsis:"Seorang pencari emas tunggal bernama Aatami menemukan emas dan pergi ke kota terdekat. Sepanjang jalan, dia bertemu dengan satu peleton pasukan Nazi yang berkeliling wilayah Lapland melakukan taktik penghancuran bumi hangus di pemukiman terdekat. Para prajurit menemukan jarahan emas Aatami dan mencoba mengambilnya darinya. Tanpa sepengetahuan mereka, Aatami adalah seorang veteran Perang Musim Dingin yang terampil dan bertekad untuk mempertahankan diri dengan segala cara.",
        Skor:"6.9",
        Author:"Jalmari Helander",
        Genre:"Action, War",
        WatchUrl:"https://77.105.142.75/movie/sisu-2023/",
        RevUrl:"https://www.rottentomatoes.com/m/sisu_2022"
    },
    {
        id: 7,
        imageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg",
        DiaimageUrl:"https://www.themoviedb.org/t/p/original/53Dg9uAvLjXMkAk4rFxHzdONwy6.jpg",
        title:"Spider-Man: Into the Spider-Verse",
        Year:"2018",
        duration:"1h 57m",
        synopsis:"Setelah gigitan laba-laba radioaktif memberinya kekuatan super, remaja Brooklyn Miles Morales (Shameik Moore) menjadi satu-satunya Spider-Man. Ketika pintu gerbang ke multiverse terbuka, Miles segera menyadari bahwa dia bukan satu-satunya pahlawan super laba-laba di luar sana, karena dia bertemu dengan banyak versi berbeda dari dirinya yang ditarik dari alam semesta lain, termasuk Peter Parker (Jake Johnson) asli dan Gwen Stacy ( Hailee Steinfeld). Bersama-sama mereka melawan Kingpin (Liev Schreiber) yang jahat dan berusaha menyelamatkan dunia.",
        Skor:"8.4",
        Author:"Jalmari Helander",
        Genre:"Superhero, Action, Sci-Fi",
        WatchUrl:"https://77.105.142.75/movie/spider-man-into-the-spider-verse-2018/",
        RevUrl:"https://www.rottentomatoes.com/m/spider_man_into_the_spider_verse"
    },
    {
        id: 7,
        imageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
        DiaimageUrl:"https://www.themoviedb.org/t/p/original/oihnoMVJHcdmUe0FbxWbwk1YbGZ.jpg",
        title:"Avengers: Endgame",
        Year:"2019",
        duration:"3h 1m",
        synopsis:"Setelah peristiwa Perang Infinity meninggalkan setengah dari alam semesta dalam reruntuhan, Avengers yang tersisa harus bekerja sama untuk merekrut sekutu lama dan baru, dan mengumpulkan semua kekuatan dan sumber daya mereka yang tersisa untuk mengalahkan raksasa gila Thanos dan membawa teman-teman mereka kembali dari tepi jurang. terlupakan. Disutradarai oleh Anthony dan Joe Russo dan dibintangi oleh pemeran ansambel yang mencakup Robert Downey Jr., Chris Hemsworth, Mark Ruffalo, Chris Evans dan bintang-bintang utama dari film-film Marvel sebelumnya.",
        Skor:"8.4",
        Author:"Russo Brothers",
        Genre:"Action, Sci-Fi, Adventure",
        WatchUrl:"https://77.105.142.75/movie/avengers-endgame-2019/",
        RevUrl:"https://www.rottentomatoes.com/m/avengers_endgame"
    },
    {
        id: 9,
        imageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/6yoghtyTpznpBik8EngEmJskVUO.jpg",
        DiaimageUrl:"https://www.themoviedb.org/t/p/original/agTn7CVFmuBEXN6e4TKTDqTv0CE.jpg",
        title:"Se7en",
        Year:"1995",
        duration:"2h 7m",
        synopsis:"Ditetapkan dalam visi neraka kota seperti New York. William Somerset, seorang spesialis pembunuhan hanya satu minggu dari pensiun yang memang layak. Tetapi pensiunnya Somerset harus menunggu satu kasus terakhir di mana dia bekerja sama dengan jagoan muda David Mills (Brad Pitt), detektif yang berapi-api akan menggantikannya di akhir minggu. Seorang pembunuh berantai yang kejam melakukan pembunuhan yang mengerikan, memilih korban yang mewakili tujuh dosa mematikan. Somerset awalnya menolak untuk mengambil kasus tersebut, menyadari bahwa akan ada lima pembunuhan lagi, khotbah mengerikan tentang nafsu, kemalasan, kesombongan, murka, dan iri hati yang dihadirkan oleh orang gila ke dunia yang penuh dosa.",
        Skor:"8.6",
        Author:"David Fincher",
        Genre:"Crime, Mystery, Thriller",
        WatchUrl:"https://77.105.142.75/movie/se7en-1995/",
        RevUrl:"https://www.rottentomatoes.com/m/seven"
    },
    {
        id: 9,
        imageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
        DiaimageUrl:"https://www.themoviedb.org/t/p/original/6uSPcdGNA2A6vJmCagXkvnutegs.jpg",
        title:"Whiplash",
        Year:"2014",
        duration:"1h 47m",
        synopsis:"Seorang drummer jazz muda, Andrew, mengalami cobaan berat ketika dia direkrut oleh seorang instruktur yang pencarian kesempurnaannya yang pantang menyerah dapat menghancurkan keduanya. Bertekad untuk membuat nama untuk dirinya sendiri tidak peduli apa yang diperlukan, dia mendaftar di konservatori musik Pantai Timur yang bergengsi, dan bakatnya dengan cepat menarik perhatian Terence Fletcher. Pemimpin ansambel jazz top sekolah, Fletcher segera mentransfer Neyman ke bandnya, memberi drummer muda yang ambisius itu kesempatan untuk mencapai kehebatan sejati.",
        Skor:"8.5",
        Author:"Damien Chazelle",
        Genre:"Drama, Music",
        WatchUrl:"https://77.105.142.75/movie/whiplash-2014/",
        RevUrl:"https://www.rottentomatoes.com/m/whiplash_2014"
    },
    {
        id: 7,
        imageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
        DiaimageUrl:"https://www.themoviedb.org/t/p/original/5icxR4X8GFVVWmJ88NFu8LX8B1Z.jpg",
        title:"Pulp Fiction",
        Year:"1994",
        duration:"2h 34m",
        synopsis:"Seorang pembunuh bayaran pencinta burger, rekan filosofisnya, seorang penjahat gangster yang kecanduan narkoba dan seorang petinju yang lusuh berkumpul dalam aksi kejahatan komedi yang luas ini. Petualangan mereka terbentang dalam tiga cerita yang dengan cerdik berjalan bolak-balik dalam waktu.",
        Skor:"8.9",
        Author:"Quentin Tarantino",
        Genre:"Thriller, Crime, Aciton",
        WatchUrl:"https://77.105.142.75/movie/pulp-fiction-1994/",
        RevUrl:"https://www.rottentomatoes.com/m/pulp_fiction"
    },
    {
        id: 7,
        imageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/7sfbEnaARXDDhKm0CZ7D7uc2sbo.jpg",
        DiaimageUrl:"https://www.themoviedb.org/t/p/original/jTLuJbn90WrKFDQSqnRm0b42r8t.jpg",
        title:"Inglourious Basterds",
        Year:"2009",
        duration:"2h 33m",
        synopsis:"Sekelompok pembunuh Nazi yang keras mengintai mangsanya di Prancis yang diduduki Nazi saat seorang pemilik bioskop Yahudi merencanakan untuk menjatuhkan perwira SS berpangkat tinggi selama pemutaran perdana resmi film propaganda Jerman yang terkenal. Misi Raine adalah menimbulkan rasa takut di hati Adolf Hitler dengan membunuh secara brutal sebanyak mungkin angsa- steppers mungkin, atau mati mencoba. Untuk mencapai tujuan itu, Lt. Raine merekrut tim pembunuh berdarah dingin yang kejam yang dikenal sebagai “The Basterds“.  Ketika Basterds membuat rencana eksplosif untuk mengalahkan Nazi sebanyak mungkin di pemutaran perdana.",
        Skor:"8.3",
        Author:"Quentin Tarantino",
        Genre:"Drama, Thriller, War",
        WatchUrl:"https://77.105.142.75/movie/inglourious-basterds-2009/",
        RevUrl:"https://www.rottentomatoes.com/m/inglourious_basterds"
    },
    {
        id: 7,
        imageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/2IRjbi9cADuDMKmHdLK7LaqQDKA.jpg",
        DiaimageUrl:"https://www.themoviedb.org/t/p/original/wpwk7x5xfUg8VZGJBG2WRzhFpCB.jpg",
        title:"All Quiet on the Western Front",
        Year:"2022",
        duration:"2h 27m",
        synopsis:"Edward Berger menyutradarai film yang diadaptasi dari novel anti-perang karya Erich Maria Remarque. Paul Bäumer mendaftar di Angkatan Darat karena versi romantis dari Perang Dunia Pertama yang dia dan teman-temannya yakini benar. Tidak lama kemudian keyakinan ini hancur. Paul didorong ke dalam parit, hampir tidak terlatih dan bahkan kurang diperlengkapi. Hanya dengan bantuan seorang veteran perang dia bertahan pada hari pertama, melihat secara langsung kenyataan tentang apa sebenarnya perang itu. ",
        Skor:"7.8",
        Author:"Edward Berger",
        Genre:"Drama, War",
        WatchUrl:"https://77.105.142.75/movie/all-quiet-on-the-western-front-2022/",
        RevUrl:"https://www.rottentomatoes.com/m/all_quiet_on_the_western_front_2022"
    },
    {
        id: 7,
        imageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/o0lO84GI7qrG6XFvtsPOSV7CTNa.jpg",
        DiaimageUrl:"https://www.themoviedb.org/t/p/original/mGK4FCfdJ3qUi848RcrheqdRsPk.jpg",
        title:"The Green Mile",
        Year:"1999",
        duration:"3h 9m",
        synopsis:"Pada tahun 1935, narapidana di Cold Mountain Correctional Facility menyebut Death Row sebagai The Green Mile karena linoleum hijau tua yang menutupi lantai. Paul Edgecomb (Tom Hanks) adalah kepala penjaga di Green Mile ketika seorang narapidana baru ditahan: John Coffey (Michael Clarke Duncan), dihukum karena pembunuhan sadis terhadap dua gadis muda. Terlepas dari ukuran tubuhnya dan kejahatan menakutkan yang dia lakukan, Coffey tampaknya adalah orang yang baik hati dan santun yang berperilaku lebih seperti anak yang tidak bersalah daripada penjahat yang keras. Segera Edgecomb dan dua rekan penjaganya, Howell (David Morse) dan Stanton Barry Pepper), melihat sesuatu yang aneh tentang Coffey: dia mampu melakukan keajaiban penyembuhan di antara sesama narapidana, membuat mereka bertanya-tanya seperti apa. orang yang dia bisa, dan jika dia bisa melakukan kejahatan yang dituduhkan padanya. The Green Mile juga dibintangi James Cromwell sebagai sipir; Michael Jeter, Sam Rockwell, dan Graham Greene sebagai narapidana yang menunggu kencan dengan kursi listrik; dan Harry Dean Stanton sebagai wali yang cerdas.",
        Skor:"8.6",
        Author:"Frank Darabont",
        Genre:"Fantasy, Drama, Crime",
        WatchUrl:"https://77.105.142.75/movie/the-green-mile-1999/",
        RevUrl:"https://www.rottentomatoes.com/m/green_mile"
    },
    {
        id: 7,
        imageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
        DiaimageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/3Tf8vXykYhzHdT0BtsYTp570JGQ.jpg",
        title:"The Godfather",
        Year:"1972",
        duration:"2h 55m",
        synopsis:"Populer dipandang sebagai salah satu film Amerika terbaik yang pernah dibuat, kisah kejahatan multi-generasi The Godfather adalah batu ujian sinema: salah satu film yang paling banyak ditiru, dikutip, dan dicerca sepanjang masa. Marlon Brando dan Al Pacino masing-masing berperan sebagai Vito Corleone dan putra bungsunya, Michael. Saat itu akhir 1940-an di New York dan Corleone, dalam istilah kejahatan terorganisir, adalah ayah baptis atau don, kepala keluarga Mafia.",
        Skor:"9.2",
        Author:"Francis Ford Coppola",
        Genre:"Crime, Drama",
        WatchUrl:"https://77.105.142.75/movie/the-godfather-1972/",
        RevUrl:"https://www.rottentomatoes.com/m/the_godfather"
    },
    {
        id: 7,
        imageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/fTuxNlgEm04PPFkr1xfK94Jn8BW.jpg",
        DiaimageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/jhWbYeUNOA5zAb6ufK6pXQFXqTX.jpg",
        title:"Hacksaw Ridge",
        Year:"2016",
        duration:"2h 19m",
        synopsis:"Medic Angkatan Darat Amerika Perang Dunia II yang taat beragama dan religius: Desmond T. Doss , yang bertugas selama Pertempuran Okinawa, menolak untuk membunuh orang dan menjadi orang pertama dalam sejarah Amerika yang menerima Medali Kehormatan tanpa melepaskan tembakan.",
        Skor:"8.1",
        Author:"Mel Gibson",
        Genre:"Drama, War",
        WatchUrl:"https://77.105.142.75/movie/hacksaw-ridge-2016/",
        RevUrl:"https://www.rottentomatoes.com/m/hacksaw_ridge"
    },
    {
        id: 7,
        imageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/mZuAPY4ETMQPHhCXIcJ90kd6RaS.jpg",
        DiaimageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
        title:"The Joker",
        Year:"2019",
        duration:"2h 2m",
        synopsis:"Dalam kisah asal yang meresahkan, Arthur Fleck (Joaquin Phoenix) ada di pinggiran masyarakat dan sama sekali diabaikan oleh orang lain. Keberadaannya yang terbuang mulai memengaruhi kondisi mentalnya, narasinya merupakan studi yang mengerikan tentang sejauh mana seseorang dapat terurai. Ditulis dan disutradarai oleh Todd Phillips, dibintangi oleh Robert De Niro.",
        Skor:"8.4",
        Author:"Todd Philips",
        Genre:"Crime, Drama, Thriller",
        WatchUrl:"https://77.105.142.75/movie/joker-2019/",
        RevUrl:"https://www.rottentomatoes.com/m/joker_2019"
    },
    {
        id: 7,
        imageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg",
        DiaimageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/1kLYRzVj6byWvFa3SLrAOcfgnfp.jpg",
        title:"Titanic",
        Year:"1997",
        duration:"3h 14m",
        synopsis:"Rose DeWitt Bukater yang berusia 101 tahun menceritakan kisah hidupnya di atas kapal Titanic, 84 tahun kemudian. Rose muda menaiki kapal bersama ibu dan tunangannya. Sedangkan Jack Dawson dan Fabrizio De Rossi memenangkan tiket kelas tiga di atas kapal. Rose menceritakan seluruh kisah dari keberangkatan Titanic hingga kematiannya—pada pelayaran pertama dan terakhirnya—pada 15 April 1912.",
        Skor:"7.9",
        Author:"James Cameron",
        Genre:"Drama, Romance",
        WatchUrl:"https://77.105.142.75/movie/titanic-1997/",
        RevUrl:"https://www.rottentomatoes.com/m/titanic"
    },
    {
        id: 7,
        imageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
        DiaimageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/rtEZ3JH8RjFS1b8z2pwyh9YI9WX.jpg",
        title:"Fight Club",
        Year:"1999",
        duration:"2h 19m",
        synopsis:"Edward Norton berperan sebagai pemuda yang depresi  yang telah menjadi roda penggerak kecil di dunia bisnis besar. Dia tidak menyukai pekerjaannya dan tidak merasakan imbalan darinya, sebaliknya berusaha untuk menenggelamkan kesedihannya dengan membangun apartemen yang sempurna. Suatu hari dalam penerbangan bisnis, dia menemukan Tyler Durden yang menjual sabun. Tyler tidak menaruh banyak saham di dunia materialistis, dan dia percaya bahwa seseorang dapat belajar banyak melalui rasa sakit, kemalangan, dan kekacauan. Tyler dengan riang menantang teman barunya untuk berkelahi. Semakin banyak pria yang bergabung, Fight Club menjadi sensasi bawah tanah, meskipun itu adalah rahasia yang dijaga ketat di antara para peserta.",
        Skor:"8.8",
        Author:"David Fincher",
        Genre:"Physchological, Drama, Thriller",
        WatchUrl:"https://77.105.142.75/movie/fight-club-1999/",
        RevUrl:"https://www.rottentomatoes.com/m/fight_club"
    },
    {
        id: 7,
        imageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
        DiaimageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/yu26pJwGFUyqTJWMWo1mMgBFJ0N.jpg",
        title:"Forrest Gump",
        Year:"1994",
        duration:"2h 22m",
        synopsis:"Seorang pria dengan IQ rendah telah mencapai hal-hal hebat dalam hidupnya dan hadir selama peristiwa bersejarah yang signifikan — dalam setiap kasus, jauh melebihi apa yang orang bayangkan dapat dia lakukan. Namun terlepas dari semua yang telah dia capai, satu cinta sejatinya menghindarinya. Apakah dirinya tidak cukup ?",
        Skor:"8.8",
        Author:"Robert Zemeckis",
        Genre:"Comedy, Drama, Romance",
        WatchUrl:"https://77.105.142.75/movie/forrest-gump-1994/",
        RevUrl:"https://www.rottentomatoes.com/m/forrest_gump"
    },
    {
        id: 7,
        imageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/4Zyk9d47uSk10GIEEwKjOLND3qx.jpg",
        DiaimageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/b6ko0IKC8MdYBBPkkA1aBPLe2yz.jpg",
        title:"The Shining",
        Year:"1980",
        duration:"2h 24m",
        synopsis:"seorang bocah pembunuh dalam adaptasi menakutkan Stanley Kubrick tahun 1980 dari novel horor Stephen King. Dengan istri Wendy (Shelley Duvall) dan putra paranormal Danny (Danny Lloyd) di belakangnya, penulis frustrasi Jack Torrance (Jack Nicholson) mengambil pekerjaan sebagai juru kunci musim dingin di Hotel Overlook yang terkunci di gunung dan tidak menyenangkan sehingga dia dapat menulis dengan tenang. . Sebelum Overlook dikosongkan untuk Torrances, manajer (Barry Nelson) memberi tahu Jack bahwa pengasuh sebelumnya menjadi gila dan membantai keluarganya; Jack berpikir itu bukan masalah, tapi Danny yang “bersinar“ mengisyaratkan sebaliknya.",
        Skor:"8.4",
        Author:"Stanley Kubrick",
        Genre:"Horror, Thriller",
        WatchUrl:"https://77.105.142.75/movie/the-shining-1980/",
        RevUrl:"https://www.rottentomatoes.com/m/shining"
    },
    {
        id: 7,
        imageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
        DiaimageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/7ypNUQ6Zxqi8tx6CYcyAgB5jJXt.jpg",
        title:"The Matrix",
        Year:"1999",
        duration:"2h 16m",
        synopsis:"Bagaimana jika realitas virtual tidak hanya untuk bersenang-senang, tetapi digunakan untuk memenjarakan Anda? Itulah dilema yang dihadapi joki komputer santun Thomas Anderson (Keanu Reeves) di The Matrix. Saat itu tahun 1999, dan Anderson (Neo) bekerja di bilik, mengoperasikan komputer dan melakukan sedikit peretasan di samping. Tahun sebenarnya lebih dekat ke 2199, dan tampaknya Thomas, seperti kebanyakan orang, adalah korban dari The Matrix, sistem kecerdasan buatan besar yang telah memasuki pikiran orang dan menciptakan ilusi dunia nyata, sambil menggunakan otak dan tubuh mereka. untuk energi, membuangnya seperti baterai bekas saat habis. Morpheus, bagaimanapun, yakin Neo adalah “The One“ yang dapat membuka The Matrix dan membawa orang-orangnya ke kebebasan fisik dan psikologis.",
        Skor:"8.7",
        Author:"Lana Wachowski",
        Genre:"Action, Sci-Fi",
        WatchUrl:"https://77.105.142.75/movie/the-matrix-1999/",
        RevUrl:"https://www.rottentomatoes.com/m/matrix"
    },
    {
        id: 7,
        imageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/4GDy0PHYX3VRXUtwK5ysFbg3kEx.jpg",
        DiaimageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/mjGVQvm7hSUXsklBq0Xhu5AeNhk.jpg",
        title:"Shutter Island",
        Year:"2019",
        duration:"2h 18m",
        synopsis:"Film ini dibuka pada tahun 1954 sebagai veteran Perang Dunia II dan marshal federal saat ini Teddy Daniels (Leonardo DiCaprio) dan mitra barunya, Chuck (Mark Ruffalo), feri ke Pulau Shutter, rumah sakit jiwa yang terikat air yang menampung para kriminal gila. Mereka diminta untuk menyelidiki hilangnya Rachel Solando (Emily Mortimer), seorang pasien yang dirawat di rumah sakit jiwa setelah dia membunuh ketiga anaknya. Saat Teddy menanyai Dr. Cawley (Ben Kingsley), kepala institusi, dia mulai curiga bahwa otoritas yang bertanggung jawab mungkin tidak memberinya seluruh kebenaran, dan bahwa nasib buruk mungkin menimpa semua pasien di Bangsal C yang menyeramkan. Sebuah unit yang dikhususkan untuk penghuni rumah sakit yang paling keji.",
        Skor:"8.2",
        Author:"Martin Scorsese",
        Genre:"Drama, Thriller, Mystery",
        WatchUrl:"https://77.105.142.75/movie/shutter-island-2010/",
        RevUrl:"https://www.rottentomatoes.com/m/1198124-shutter_island"
    },
    {
        id: 7,
        imageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
        DiaimageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/bzONet3OeCTz5q9WOkGjVpOHMSR.jpg",
        title:"Interstellar",
        Year:"2014",
        duration:"2h 18m",
        synopsis:"Interstellar terbuka di Bumi di masa depan yang jauh, saat Alam Pertiwi mengobarkan perang terhadap umat manusia. Kelaparan tersebar luas, dan semua sumber daya umat manusia sekarang didedikasikan untuk bertani dalam perjuangan mati-matian untuk bertahan hidup. Seorang mantan pilot dan insinyur NASA bernama Cooper (Matthew McConaughey) telah menjadi wisma untuk menghidupi putranya yang masih remaja, Tom (Timothee Chalamet) dan putrinya yang berusia 10 tahun Murph (Mackenzie Foy). Sayangnya, itu pun mulai terlihat seperti usaha yang sia-sia setelah badai pasir merusak komunitas mereka yang erat. Sementara itu, misteri yang tampaknya supranatural mulai terungkap ketika hantu yang tinggal di kamar Murph mengirimkannya serangkaian koordinat misterius.",
        Skor:"8.7",
        Author:"Christopher Nolan",
        Genre:"Adventure, Drama, Sci-Fi",
        WatchUrl:"https://77.105.142.75/movie/interstellar-2014/",
        RevUrl:"https://www.rottentomatoes.com/m/interstellar_2014"
    },
    {
        id: 7,
        imageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/aCIFMriQh8rvhxpN1IWGgvH0Tlg.jpg",
        DiaimageUrl:"https://www.themoviedb.org/t/p/w600_and_h900_bestv2/k68nPLbIST6NP96JmTxmZijEvCA.jpg",
        title:"Tenet",
        Year:"2020",
        duration:"2h 30m",
        synopsis:"Di masa depan yang tidak terlalu jauh, teknologi inovatif berkuasa. Saat negara-negara saingan bersaing untuk mendapatkan supremasi global, ancaman Perang Dunia ketiga terlalu besar untuk diabaikan karena ketegangan meningkat. Seorang agen khusus (John David Washington) dan rekannya (Robert Pattinson) menyetujui misi baru yang berisiko menggunakan kemajuan terbaru dalam perjalanan waktu dan evolusi manusia untuk menghentikan penyebab perang pada sumbernya.",
        Skor:"7.3",
        Author:"Christopher Nolan",
        Genre:"Action, Thriller, Sci-Fi",
        WatchUrl:"https://77.105.142.75/movie/tenet-2020/",
        RevUrl:"https://www.rottentomatoes.com/m/tenet"
    },



];

export default movielistData;